### ISSUE TITLE
mailanalyzer not install GLPI

### ISSUE THREAD

**Issue by guillermohaad** [tomolimo/mailanalyzer#1]
Good morning,

I have GLPI Version 0.90 

copied to plugins in GLPI /var/www/glpi/plugins/ but not shown to install? 

![mailanalyzer](https://cloud.githubusercontent.com/assets/12921805/13076647/9da35216-d481-11e5-819c-635036a6e3db.png)

**Comment by tomolimo** [comment]
Hello,
Could you send me a screen copy of the plugins folder?
Thank you,
regards,
Tomolimo

**Comment by guillermohaad** [comment]
Hello friend,

I solved the problem:

unzip the folder is as follows: mailanalyzer-1.2.2
I switch to mailanalyzer and run,
thank you

I have other plugins that have the same problem,
you can help me?

2016-02-16 7:55 GMT-05:00 tomolimo notifications@github.com:

**Comment by guillermohaad** [comment]
I solved the problem:

unzip the folder is as follows: mailanalyzer-1.2.2
I switch to mailanalyzer and run,
thank you
