### ISSUE TITLE
Question - request for help

### ISSUE THREAD

**Issue by koda0601** [tomolimo/mailanalyzer#10]
Hello,
I am using mailanalyzer plugin and works very well. You are very helpful person and hope you answer ma question ;-)
My users are rather lazy ;-) and send requests mails directly to me or my colleague. Then we forward it to glpi and your plugin replace the real requester
I want to extend this plugin to assign tech person automatically. For example if I send mail this should be automatically assigned to me. The code may be not "elegant". Could you help me with this?
I think it is similar to: if( $locUser->getFromDB( $row['id'] ) ) {
                        // set users_id 
                        $parm->input['users_id'] = $locUser->getID() ;
                        //$parm->input['_users_id_requester'] = $locUser->getID() ;
                    }
but need to know the input key... Thanks in advance ;-)

**Comment by tomolimo** [comment]
Hello,
Do you want to modify the plugin, or write a new plugin?
Anyway you may write a rule to assign automatically a technician to a ticket.
regards,
Tomolimo

**Comment by koda0601** [comment]
Hi,
just to modify the plugin..
Can you help me how to write a rule? I couldn find creator of request in
rule or I am blind ;-)

2017-03-06 11:33 GMT+01:00 tomolimo <notifications@github.com>:

**Comment by tomolimo** [comment]
Good remark, ticket writer is not in the list for criterion

**Comment by tomolimo** [comment]
so the only solution you have is to write a new plugin, (or to modify an existing plugin, but this is really bad as at each new release you'll have to redo your modification)

**Comment by koda0601** [comment]
Yes, I know that, but I always control you plugin before update ;-)
I know that must insert to glpi_tickets_users but wonder is it possible to
use $parm->input in your hook and how to read ticket creator?

2017-03-06 12:00 GMT+01:00 tomolimo <notifications@github.com>:

**Comment by tomolimo** [comment]
ticket creator (=ticket writer =email sender) is $param->input['users_id_recipient']

**Comment by koda0601** [comment]
Thanks ;-)
one more question: during your hook (mailanalyzer) is the id of ticket
know? Or is it triger before it is saved to db?
I am not familiar with plugins ...

2017-03-06 12:35 GMT+01:00 tomolimo <notifications@github.com>:

**Comment by tomolimo** [comment]
plugin_pre_item_add_mailanalyzer is before ticket creation then ticket id is not known
and
plugin_item_add_mailanalyzer is after ticket creation then id is in $parm->fields['id'],

**Comment by koda0601** [comment]
Thank you very much. It works! ;-)

2017-03-06 14:07 GMT+01:00 tomolimo <notifications@github.com>:

**Comment by tomolimo** [comment]
you're welcome
