### ISSUE TITLE
this plugin is not compatible with glpi 9.2?

### ISSUE THREAD

**Issue by sferia82** [tomolimo/mailanalyzer#12]
this plugin is not compatible with glpi 9.2?

**Comment by tomolimo** [comment]
Hello,
I've not tested it with 9.2
But I can do it today.
regards,
Tomolimo

**Comment by sferia82** [comment]
Let me know when it's available. thank you very much

**Comment by sferia82** [comment]
do you have the version updated? thank you very much.

**Comment by tomolimo** [comment]
Yes, and I'm currently testing it with the 9.2.1
It should be ready for end of week
Regards
Tomolimo

**Comment by sferia82** [comment]
thanks. :)

**Comment by sferia82** [comment]
sometimes when glpi must import a mail with a subject that exist it doesn't import. and in "receivers" --> "List of not imported emails" there are mails.
the reason is Operation failure. 
i don't understand why.

thanks.

**Comment by sferia82** [comment]
this happens when you have to add as a follow-up an email that has just arrived at an existing ticket. it adds it but it does not finish processing the mail and in receivers it appears as that it could not import the mail.

**Comment by tomolimo** [comment]
This issue is closed!
So don't hesitate to open a new one.
thank you
regards,
Tomolimo
