### ISSUE TITLE
Problem with getting message GLPI 9.2

### ISSUE THREAD

**Issue by okvok** [tomolimo/mailanalyzer#13]
Hi.
After migrating to GLPI 9.2 I've faced with next issue: when user1 sends email to user2 with Helpdesk address in CC a GLPI server registers this ticket properly and message put into the archive folder in mailbox. But when user2 reply to All (Helpdesk still in CC) the message properly attached to the ticket mentioned above like a followup and stays keep in the Inbox folder without removing into archive folder. When I am trying to Get email manually in Receivers action it gets me an Error for the message from User2. Therefore emails sort of "Reply to All" are collecting in Inbox.
PS: After updating your plugin Mail Analyzer to 1.3.2 nothing changed.

**Comment by tomolimo** [comment]
Hello
Could you please provide some screen shots?
Thank you
Regards
Tomolimo

**Comment by okvok** [comment]
user1 to  user2 and CC: helpdesk:
![image](https://user-images.githubusercontent.com/20252855/32404422-6c465f6a-c160-11e7-9443-b82069caa87b.png)

reply All from user2:
![image](https://user-images.githubusercontent.com/20252855/32404439-a26b5726-c160-11e7-9a27-d178b6e1f6f1.png)

How it looks properly in GLPI:
![image](https://user-images.githubusercontent.com/20252855/32404591-4df34534-c163-11e7-96bc-0873fa241952.png)

Receiver settings with the folder for archive:
![image](https://user-images.githubusercontent.com/20252855/32404469-210ddd42-c161-11e7-8e38-f53f4175a53d.png)

Installed plugin:
![image](https://user-images.githubusercontent.com/20252855/32404477-42164a6a-c161-11e7-8860-d6a16c88d9a8.png)

Error when trying to get messages manually:
![image](https://user-images.githubusercontent.com/20252855/32404522-e18fb540-c161-11e7-9cfa-edb3e8c038c0.png)


Replied All messages stay keep in Inbox:
![image](https://user-images.githubusercontent.com/20252855/32404573-e06b4886-c162-11e7-9565-3fd75a8517fe.png)

**Comment by tomolimo** [comment]
Hello
Thank you for the pictures I have a better idea of what going on. 
1. The error message could be normal 
1. I'm going to make new tests on my side and I'll keep you updated. 
Thank you 
Tomolimo

**Comment by okvok** [comment]
Hello!
Do you have any news for me?
It's very inconveniently :( But we can't work without your plugin.

**Comment by tomolimo** [comment]
Hello,
I'll test this tomorrow. Today is Sunday :)
Thank you 
Regards 
Tomolimo

**Comment by tomolimo** [comment]
Hello,
Root cause is found: the plugin is only managing emails like if the receiver was using POP (in this case no folder).
I'm going to work on this to add this feature into the plugin.
Regards,
Tomolimo

**Comment by okvok** [comment]
Ohhh!!! Create ! Sounds good! When you gonna make changes and update plugin?

**Comment by tomolimo** [comment]
Hello,
Could you check in the php error logs?
You should get some errors, could yo give me them back?
Thank you
regards,
Tomolimo

**Comment by okvok** [comment]
>Понедельник,  6 ноября 2017, 14:07 +03:00 от tomolimo <notifications@github.com>:
>
>Hello,
>Could you check in the php error logs?
>You should get some errors, could yo give me them back?
>Thank you
>regards,
>Tomolimo
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


All the best,

ILDAR
