### ISSUE TITLE
Not merging emails in 9.2.1

### ISSUE THREAD

**Issue by ensonb** [tomolimo/mailanalyzer#16]
Hi, I've updated 9.1.4 into a 9.2.1  version of GLPI and installed a newer version of the mailanalyzer plugin, but every reply via email is creating a new ticket like if the plugin is not installed.

**Comment by ensonb** [comment]
Hi

I've truncated the table `glpi_plugin_mailanalyzer_message_id` reinstalled the plugin and it's working now.

thanks

**Comment by jpsbatista** [comment]
@ensonb How did you trunk the table?
Send the procedure, please.

**Comment by ensonb** [comment]
@jpsbatista Hi

**Make sure you do a backup first**
 - I've deleted the plugin
 - I've logged into the mysql database, could be via phpMyadmin or via terminal and emptied  the table 
   glpi_plugin_mailanalyzer_message_id:

   `TRUNCATE TABLE 'glpi_plugin_mailanalyzer_message_id' `
 - Then reinstalled the plug_in.
regards
