### ISSUE TITLE
use email passed in special field instead of the email sender

### ISSUE THREAD

**Issue by andreaontheweb** [tomolimo/mailanalyzer#18]
Hello' I'm looking for a solution to my problem.
I'm sending an email for generating ticket anonymous to a glpi receiver.
I'd like to use your plugin for change the email address or the requester using the provided one instead of the mail sender, this because I use the same smtp server.
But as a read in your documentation special chars (@) are not allowed.
Any suggestions?

**Comment by tomolimo** [comment]
Hello @andreaontheweb 

> But as a read in your documentation special chars (@) are not allowed.

Where did you see this?
I can't remember,

thank you
Regards,
Tomolimo

**Comment by andreaontheweb** [comment]
Maybe I misunderstood your code. 
Anyway I need to receiving an anonymous new email and use the ##form field as requester.
Do you think is possible with your plugin?

**Comment by tomolimo** [comment]
Hello,

Yes, it should be possible if your ##From respect the so called 'OnBehalfOf':

![image](https://cloud.githubusercontent.com/assets/7569958/21516412/50304228-ccd8-11e6-81dc-a2c80393e087.png)

As seen on the screen copy, when you want to forward an email 'OnBehalfOf' to a GLPI receiver, you need to have `##From: "LastName, FirstName" <blabla@domain.com>`  for example (see below for more examples), in the message that is forwarded. 
    
A regular expression:
 `/##From\s*:\s*(["']?(?'last'[\w.\-' ]+)[, ]\s*(?'first'[\w+.\-' ]+))?.*?(?'email'[\w_.+\-]+@[\w\-]+\.[\w\-.]+)?\W*$/im` 
will verify this syntax, so it must be really like shown. 

 In `LastName` authorized chars are: 

- letters from '`a`' to '`z`', 
- underscores '`_`', 
- digits from '`0`' to '`9`', 
- dashes '`-`', whitespaces '` `' 
- single quotes '`'`'. 

And in `FirstName` authorized chars are: 

- letters from '`a`' to '`z`', 
- underscores '`_`', 
- digits from '`0`' to '`9`', 
- dashes '`-`', whitespaces '` `' 
- dots '`.`'. 

And the email part must be compliant to standard email notation.

The comparison is case insensitive.

1. The GLPI user who matches `LastName, FirstName` must be unique in GLPi
1. This user must have at least one email address.
1. The user must be active and not deleted.

Examples of good expressions:
##From: Olimo, Tom
##From : Olimo Tom <tom@domain.com>
##from: 'Olimo Tom'  tom.olimo@domain.com
##from : "Olimo, Tom" "tom.olimo@domain.com"
and so on

regards,
Tomolimo

**Comment by andreaontheweb** [comment]
Mm I'm receiving email from anonymous so I have no user to compare with.

**Comment by tomolimo** [comment]
the user to compare with is the one of the users already defined in GLPI

**Comment by andreaontheweb** [comment]
I'm missing something. 
So sorry.
I have enabled the allow anonymous ticket creation option.
So anyone send an email could create a ticket.
I'd like to use your plugin for change the sender with the fields present in the ##from: tag

**Comment by tomolimo** [comment]
Hello @andreaontheweb 
What you need to understand is that the 

> ##from: tag

must represent a valid GLPI user. If so, then it's perfect just try it :smiley: 

regards,
Tomolimo

**Comment by andreaontheweb** [comment]
Dear to molino,  tank's for your support, but I tried to learn more about your wonderful plugin.
But I don't thin is what I need. 
I'm able to match añ email ticket with an user but what I really need is change the email of the reply to the user, not only assign newly created ticket to an user.
Thank 's again.

**Comment by tomolimo** [comment]
You're welcome
