### ISSUE TITLE
Plugin replacing Sender by CC

### ISSUE THREAD

**Issue by edsonct** [tomolimo/mailanalyzer#19]
Hi,
Thanks for plugin.
But I have a problem.
When sender send mail with CC the the GLPI open a ticket and put CC as Sender.
Can you help me?
Regards

**Comment by tomolimo** [comment]
Hello
Could you post glpi configuration and glpi logs?
Thank you 
Tomolimo

**Comment by edsonct** [comment]
Hello,
Thanks for reply tomolimo, sorry.
GLPI Version 92.2.
Log Files

tail -f /var/www/html/glpi/files/_log/php-errors.log
  plugin_version_mailanalyzer-master method must be defined!
2018-04-25 15:04:19 [2@edsoftitticket]
  From Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1374
  plugin_version_mailanalyzer-master method must be defined!
2018-04-25 15:04:20 [2@edsoftitticket]
  From Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1374
  plugin_version_mailanalyzer-master method must be defined!
2018-04-25 15:04:21 [2@edsoftitticket]
  From Plugin::getInfo() in /var/www/html/glpi/inc/plugin.class.php line 1374
  plugin_version_mailanalyzer-master method must be defined!

**Comment by tomolimo** [comment]
Hello @edsonct 
Where did you get this version of the plugin?
Did you download it from the released section? Or did you download it from the master branch? Master branch is for development only, not for production
You must download from here: https://github.com/tomolimo/mailanalyzer/releases if you want to get support!
Thank you
Regards,
Tomolimo

**Comment by edsonct** [comment]
Tomolio,

I'm so sorry for answer for you so slow.
It's work for me.
Thank you so much

**Comment by tomolimo** [comment]
Hello @edsonct 
Thank you for your answer,
Regards,
Tomolimo
