### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by edsonjb** [tomolimo/mailanalyzer#21]
Hello, are you planning to upgrade to 9.3? Thank you.

**Comment by tomolimo** [comment]
Hello @edsonjb 

Yes, but not before end of summer.
In the meanwhile, you may test the plugin with 9.3, don't you?

Thank you,
Regards,
Tomolimo

**Comment by mohamed-riadh** [comment]
Hello , 
Is there an intention to launch the update soon?
the upgrade of our version of glpi to 9.3  is blocked until all installed plugin will be updated
thank you

**Comment by tomolimo** [comment]
Hello @mohamed-riadh 
Currently the plugin has not been tested with 9.3, but you may do a try :)
And the schedule for the release is end of the year.
But at anytime, you may do the tests and report to us: it will accelerate the release :)
Thank you
Regards,
Tomolimo

**Comment by mohamed-riadh** [comment]
Thank you for reply 
i will prepare a test enveriment to do the upgrade ,and will notify you for results
cordialy

**Comment by vilmarap** [comment]
Hello, I installed the plugin in version 9.3, but it gets incompatible with the version and ends up presenting problem to add a solution, category or technical group.

**Comment by vilmarap** [comment]
When I disable this plugin, the call categories options reappear and I can add the solution to the call.

**Comment by ti-wh1** [comment]
I've tested with 9.4 and got this error. Maybe it's a good idea to make it compatible straight to 9.4 and it should be to 9.3 by default.

==> glpi-error.log <==
[Fri Feb 15 04:01:23.392792 2019] [php7:error] [pid 27161] [client 177.97.208.214:52858] PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /var/www/glpi/inc/itilfollowup.class.php:321\nStack trace:\n#0 /var/www/glpi/inc/commondbtm.class.php(1100): ITILFollowup->prepareInputForAdd(Array)\n#1 /var/www/glpi/plugins/mailanalyzer/hook.php(364): CommonDBTM->add(Array)\n#2 /var/www/glpi/inc/plugin.class.php(1044): PluginMailAnalyzer::plugin_pre_item_add_mailanalyzer(Object(Ticket))\n#3 /var/www/glpi/inc/commondbtm.class.php(1091): Plugin::doHook('pre_item_add', Object(Ticket))\n#4 /var/www/glpi/inc/mailcollector.class.php(726): CommonDBTM->add(Array)\n#5 /var/www/glpi/front/mailcollector.form.php(77): MailCollector->collect('1', 1)\n#6 {main}\n  thrown in /var/www/glpi/inc/itilfollowup.class.php on line 321, referer: https://glpi.wh1.com.br/front/mailcollector.form.php?id=1
[Fri Feb 15 04:08:09.545148 2019] [php7:error] [pid 27231] [client 177.97.208.214:53134] PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /var/www/glpi/inc/itilfollowup.class.php:321\nStack trace:\n#0 /var/www/glpi/inc/commondbtm.class.php(1100): ITILFollowup->prepareInputForAdd(Array)\n#1 /var/www/glpi/plugins/mailanalyzer/hook.php(364): CommonDBTM->add(Array)\n#2 /var/www/glpi/inc/plugin.class.php(1044): PluginMailAnalyzer::plugin_pre_item_add_mailanalyzer(Object(Ticket))\n#3 /var/www/glpi/inc/commondbtm.class.php(1091): Plugin::doHook('pre_item_add', Object(Ticket))\n#4 /var/www/glpi/inc/mailcollector.class.php(726): CommonDBTM->add(Array)\n#5 /var/www/glpi/inc/mailcollector.class.php(1840): MailCollector->collect('1')\n#6 /var/www/glpi/inc/crontask.class.php(829): MailCollector::cronMailgate(Object(CronTask))\n#7 /var/www/glpi/front/crontask.form.php(49): CronTask::launch(-1, 1, 'mailgate')\n#8 {main}\n  thrown in /var/www/glpi/inc/itilfollowup.class.php on line 321, referer: https://glpi.wh1.com.br/front/crontask.form.php?id=9

**Comment by Skouat** [comment]
Hi all,
have a look on the PR #27

**Comment by tomolimo** [comment]
Hello,
Thanks to @Skouat, it seems to be fixed
Feel free to re-open if not.
