### ISSUE TITLE
issue with GLPI 9.2.4

### ISSUE THREAD

**Issue by moalkaabi** [tomolimo/mailanalyzer#22]
Hello ,
I have installed the plugin in glpi 9.2.4 , but still I'm facing issue with ticket duplication.
replying to a mail create a new ticket.

regards,

**Comment by tomolimo** [comment]
Hello,
Could you give more details above configuration of glpi? 
Could you check the log files? 
Could you also give steps to reproduce the issue? 
Thank you 
Regards 
Tomolimo

**Comment by DanielGrilo** [comment]
Hello,

Here is the mistake I made
![Annotation 2019-03-12 100159](https://user-images.githubusercontent.com/48473388/54187557-265ae480-44ae-11e9-9d0c-397a3bc1d0ac.jpg)

**Comment by tomolimo** [comment]
Hello,
Could you give more details above configuration of GLPI?
Could you also give steps to reproduce the issue?
Thank you
Regards
Tomolimo

**Comment by DanielGrilo** [comment]
i'm in version 9.4.1.1

**Comment by tomolimo** [comment]
Hello @DanielGrilo 
Is this issue linked with the issue above?
If not could you open another issue, instead of mixing problems?
Thank you
Regards,
Tomolimo

**Comment by DanielGrilo** [comment]
Hello @tomolimo 
Yes the problem is exactly the same
When you answer a ticket already existing instead of putting it in the tracking, it crashes. I am obliged to disable it. so I have a new ticket.

**Comment by tomolimo** [comment]
ok, I'm going to check with 9.4.1.1

**Comment by Skouat** [comment]
Hi there,
Please can you test the PR #27 and let me know if there are issues.

**Comment by tomolimo** [comment]
Thanks to @Skouat,
it seems to be fixed 
If not please feel free to re-open the issue.
