### ISSUE TITLE
Still have many duplicates - GLPI 9.4.0

### ISSUE THREAD

**Issue by SaguezAdmin** [tomolimo/mailanalyzer#29]
Hello,

We upgraded glpi to version 9.4.0 ( to a new server ) 

Your wonderful plugin was installed in our previous glpi and was working like a charm.
But now, we have lots of duplicate.

How can we provide informations, logs to see what can be wrong and if we can help solving this ?

Many thx.

Olivier

**Comment by tomolimo** [comment]
Hello @SaguezAdmin 
You may add your logs to this issue.
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello
Closing this issue as no answer has been given to my last question.
Feel free to re-open it if you want to copy/paste the log content.
Thank you
Regards,
Tomolimo
