### ISSUE TITLE
Deleting mails

### ISSUE THREAD

**Issue by Alkashee** [tomolimo/mailanalyzer#3]
Hi,

I start to use your plugin and it's very usefull !

But I got a surprise; With a reply, it add correctly the mail in the existing ticket but then it delete the mail ! I'd like to conserve the mail, how is it possible ?

Thanks you in advance ;)

**Comment by tomolimo** [comment]
Hello,
Thank you for your feedback :smiley: 
Regarding your request: as far as I know: isn't it the default behavior of the GLPi mailgate? To not keep in 'inbox' the emails that have been integrated?
regards,
Tomolimo

**Comment by Alkashee** [comment]
Hello,

I don't know for version <0.90 but in 0.90 you can specify optionals archives folders for accepted and refused mails. the mails that your plugin handle don't come to theses folders after processing :(

**Comment by tomolimo** [comment]
Yes right my remark was for 0.83.8, then this is a new feature request :)
I'll implement it with the same behavior than GLPi.
Thank you
Regards,
Tomolimo

**Comment by Alkashee** [comment]
Thanks a lot, I'll stay tuned about it !!

**Comment by achekmez** [comment]
Hello, this plugin seems to be very useful, but it seems it have difficultes cheking GLPI version since 9.1 (not 0.91)

**Comment by tomolimo** [comment]
It seems to be a new issue :), then open a new issue: don't use existing ones or at the after a while nobody will know what is it about. 
thank you.

**Comment by achekmez** [comment]
I am new on GitHub, so sorry for some mestakes. I will try to open new issue.

**Comment by tomolimo** [comment]
no problem :)
