### ISSUE TITLE
GLPI 9.4.2

### ISSUE THREAD

**Issue by KespAdmin** [tomolimo/mailanalyzer#30]
Hi, this isn't working on 9.4.2, not showing even in plugins list.

**Comment by tomolimo** [comment]
Hello @KespAdmin 
Could you look into the /files/_log/ folder at the file php-errors.log and report any errors from it?
Thank you,
Regards,
Tomolimo

**Comment by KespAdmin** [comment]
Hi @tomolimo, this is the log:

plugin_version_mailanalyzer-master method must be defined!  {"user":"xxx@xxx"}

**Comment by tomolimo** [comment]
Hello,
You have installed the plugin doing a clone of the master branch, where there are already prepared releases :smiley: 
Check this: https://github.com/tomolimo/mailanalyzer/releases
Thank you to take the running packages from the official releases.
Regards
Tomolimo
