### ISSUE TITLE
Is it possible to add watchers via a tag?

### ISSUE THREAD

**Issue by bigben386** [tomolimo/mailanalyzer#33]
Hi,
I have written a GMail plugin that creates prepared emails with the correct ##FROM: tag that is forwarded to the GLPI ticket email address. Sometimes the source email has several people on CC. Is it possible there is a similar tag that can be used for watchers so I don't have to CC them on the forwarded ticket email?

**Comment by tomolimo** [comment]
Hello,
I did exactly this, but for an internal only plugin (plugin that will never be published)... 
It is call ##CC, and it can also manage groups :)
I can extract the part that manages the ##CC and include it into mailanalyzer.
Give me some times to do this.
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
fixed by #34

**Comment by bigben386** [comment]
Just wanted to say thanks @tomolimo . I updated our Gmail addon to add the #CC header and everything is working great!

**Comment by tomolimo** [comment]
Hello @bigben386 
Good to know, thank you for your feedback 😃 
Regards,
Tomolimo
