### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by phamorais** [tomolimo/mailanalyzer#38]
Good Morning
When using the plugin in GLPI 9.4.6 and sending an email to a "CC 'recipient, the user in the" CC "field is not added to the email. Should he be added?

**Comment by tomolimo** [comment]
Hello @phamorais 
Could you describe step by step the issue so that I can reproduce it?
Thank you,
Regards,
Tomolimo

**Comment by phamorais** [comment]
Hi

- Installed the plugin (version 1.6.4) with GLPI version 9.4.6
- Enabled the plugin in GLPI;
- I sent an email to user @ gmail.com, with copy to john@gmail.com

The Plugin acted correctly and did not duplicate the call, but did not add john@gmail.com as an observer to the call.

This was the result I expected.


Sorry if I'm missing something.

**Comment by tomolimo** [comment]
Hello @phamorais 
Do you mean that you sent two identical emails to GLPI?
Thank you
Regards,
Tomolimo

**Comment by phamorais** [comment]
HI @tomolimo 

I want that when someone sends the email to my myaccont@gmail.com account the call is opened at GLPI (and it already happens).

However, when the customer sends the email to myaccont@gmail.com, and adds an email in the "CC" field (with copy), the user's email with copy is not being included in the ticket.

**Comment by tomolimo** [comment]
Hello @phamorais 

I need to understand a little bit more :)
Is it like following:
1. User A send to GLPI an email E to create a ticket
1. This E email creates a ticket T1 in GLPI 
1. User A re-send the same email and add in CC User B
1. GLPI will not create a new ticket (as T1 is already created from the email E: thanks to plugin)
1. what is expected is that GLPI will add User B as watcher for T1?

thank you
regards,
Tomolimo

**Comment by phamorais** [comment]
exactly!

However, user B does not need to be registered in my GLPI.

For that, I use the option Setup> General> Assistance>

- Allow anonymous ticket creation (helpdesk.receiver)
- Allow anonymous followups (receiver)

that way I allow users not registered with my GLPI to see the tickets.

However, when I enabled the plugin, it is not putting user B (not registered) in the Observer field.

**Comment by tomolimo** [comment]
Hello @phamorais 
Did you also do a test with a registered user B? To know if it will added into the ticket
Thank you
regards,
Tomolimo

**Comment by phamorais** [comment]
Hi @tomolimo 
Yes.

If I answer the email with User B, instead of GLPI including a new follow-up, he opened a new ticket.


Prints example:
Send e-mail, to USER A, and CC to user B

![image](https://user-images.githubusercontent.com/35368369/83592660-35093d80-a531-11ea-865a-7eb044272214.png)


User B, has not been added to the Ticket.

**Comment by phamorais** [comment]
Hello !

I contacted Teclib support and they solved my problem. The situation I reported above will be resolved in GLPI 9.5, thank you very much for your promptness!

**Comment by tomolimo** [comment]
you're welcome
