### ISSUE TITLE
ARSURVEYS

### ISSUE THREAD

**Issue by Octogorum** [tomolimo/mailanalyzer#4]
Hi.
I hope you can help me.
I've installed ARSURVEYS plugin in directory ,but GLPI doesn't show Arsurveys plugin , I mean I cant see the options : (Install , Activate ) in Plugins tab.
I don't know if I've unzipped wrong in directory, other plugins run correctly except ARSURVEY.
Can you tell me how is the correct mode to install it?
I'm using glpi v 0.90.1
Thanks in advance.

**Comment by tomolimo** [comment]
You are not in the right area to post about arsurveys :(
