### ISSUE TITLE
Compatibility - GLPI 9.5

### ISSUE THREAD

**Issue by phamorais** [tomolimo/mailanalyzer#40]
Hello @tomolimo ! 

Is version 1.6.4 compatible with the new GLPI 9.5?

In my development environment, there is no impediment to enabling it.

But in the description of the plugin the information is compatible with 9.4

![image](https://user-images.githubusercontent.com/35368369/86935388-26efa380-c113-11ea-9de5-4a5cdf5c358f.png)

**Comment by tomolimo** [comment]
Hello,
Not yet compliant with 9.5
Regards,
Tomolimo

**Comment by felipepimentel08** [comment]
Hello tomolimo.

Would there be any forecast for the good (update) operation in version 9.5.1?

**Comment by LCBLondon** [comment]
I had a quick look and it seems that one of the feature on which this plugin rely is no longer available in 9.5/9.5.1.
$parm->input['_head'] is no longer in the data model provided by GLPI to the plugin.
As this is required to get the message IDs it it unlikely that this plugin will quickly be updated to be compatible with 9.5

**Comment by LCBLondon** [comment]
Not sure it will fix the issue but you can try to edit the file:
`glpi/inc/mailcollector.class.php`
and add:
`$tkt['_head'] = $headers;`
after line 1036:
   `1036       $tkt['_message']  = $message;`
   `1037       $tkt['_head'] = $headers;`
   `1038       if (!Toolbox::seems_utf8($body)) {`

**Comment by senn6k** [comment]
> Hello,
> Not yet compliant with 9.5
> Regards,
> Tomolimo

Dear Tomolimo,

when will this be available for 9.5  version , looking forward for this plugin available for 9.5. excellent work and saves lot of efforts..

**Comment by tomolimo** [comment]
Hello,
Thank you to use the plugin, I'm glad to see that it is really used :smiley: 
Currently, we have no planning for the upgrade of the plugins, due to Covid-19, I'm working short time (at 40%), and of course I only have time for running operations and not for evolutions. Sorry for that.
I'll come back to you as soon as I'll have more time to spend on updates.
But anyway, feel free to do PR on the repo.
Thank you very much,
Regards,
Tomolimo

**Comment by fgendorf** [comment]
> Not sure it will fix the issue but you can try to edit the file:
> `glpi/inc/mailcollector.class.php`
> and add:
> `$tkt['_head'] = $headers;`
> after line 1036:
> `1036 $tkt['_message'] = $message;`
> `1037 $tkt['_head'] = $headers;`
> `1038 if (!Toolbox::seems_utf8($body)) {`

This doesn't fix because all mailgate from GLPI 9.5 was changed to Laminas\Mail

**Comment by sandromrsousa** [comment]
Hello,
Any news on update to 9.5?
Its a really usefull plugin.

**Comment by tomolimo** [comment]
Not yet, but we may start working on it in a near future

**Comment by Skouat** [comment]
On [this line](https://github.com/tomolimo/mailanalyzer/blob/master/hook.php#L253), the code wait for headers value.
Since the migration to Laminas, mailcollector has been fully refactored and the header is no more parsed to mailanalyser.

Before
```
Array
(
    [_blacklisted] => 
    [_mailgate] => 1
    [_filename] => Array
        (
        )

    [_tag] => 
    [_users_id_requester] => 79
    [_users_id_requester_notif] => Array
        (
            [use_notification] => Array
                (
                    [0] => 1
                )

        )

    [users_id] => 79
    [_auto_import] => 1
    [_do_not_check_users_id] => 1
    [_head] => Array
        (
            [from] => username@domain.tld
            [subject] => RE: Test emails
            [reply-to] => username@domain.tld
            [to] => helpdesk@domain.tld
            [message_id] => <DB8PR06MB6316141776F2B624038C73CDFE030@DB8PR06MB6316.eurprd06.prod.outlook.com>
            [tos] => Array
                (
                    [0] => helpdesk@domain.tld
                )

            [ccs] => Array
                (
                )

            [date] => 2020-10-16 11:54:38
            [references] => <DB8PR06MB6316345D0F3F19587684E3AFFE030@DB8PR06MB6316.eurprd06.prod.outlook.com> <VI1PR06MB459236FF33F86436D742F14E9B030@VI1PR06MB4592.eurprd06.prod.outlook.com>
            [in_reply_to] => <VI1PR06MB459236FF33F86436D742F14E9B030@VI1PR06MB4592.eurprd06.prod.outlook.com>
            [received] => from DB8PR06MB6473.eurprd06.prod.outlook.com (2603:10a6:10:fc::11)\nfrom DB8PR06MB6316.eurprd06.prod.outlook.com (2603:10a6:10:3e::26)\nfrom DB8PR06MB6316.eurprd06.prod.outlook.com
            [x-ms-exchange-organization-authas] => Internal
            [x-ms-exchange-organization-authmechanism] => 04
            [x-ms-exchange-organization-authsource] => DB8PR06MB6316.eurprd06.prod.outlook.com
            [x-ms-exchange-organization-scl] => -1
            [x-ms-exchange-organization-recordreviewcfmtype] => 0
            [x-ms-publictraffictype] => Email
            [x-ms-office365-filtering-correlation-id] => 059393f1-4501-4178-a100-08d871b97f5a
            [x-ms-traffictypediagnostic] => DB8PR06MB6473:
            [x-ms-oob-tlc-oobclassifiers] => OLM:1728;
            [x-microsoft-antispam] => BCL:0;
            [x-ms-exchange-crosstenant-originalarrivaltime] => 16 Oct 2020 09:54:39.1490 (UTC)
            [x-ms-exchange-crosstenant-fromentityheader] => Hosted
            [x-ms-exchange-crosstenant-id] => 2b755fa1-23d1-48f3-98fc-6fdc1dc48d69
            [x-ms-exchange-transport-crosstenantheadersstamped] => DB8PR06MB6473
            [x-ms-exchange-transport-endtoendlatency] => 00:00:01.6647703
            [x-ms-exchange-processed-by-bccfoldering] => 15.20.3477.020
        )

    [content] => <content removed>
    [_supplier_email] => 
    [name] => RE: Test emails
    [urgency] => 3
    [itemtype] => 
    [requesttypes_id] => 2
    [entities_id] => 0
    [_ruleid] => 3
    [_no_history] => 
)
```

after

```
Array
(
Array
(
    [_blacklisted] => 
    [_mailgate] => 1
    [date] => 2020-10-16 12:16:19
    [_users_id_requester] => 68
    [_users_id_requester_notif] => Array
        (
            [use_notification] => Array
                (
                    [0] => 1
                )

        )

    [users_id] => 68
    [_auto_import] => 1
    [_do_not_check_users_id] => 1
    [_message] => <message manually removed>
    [content] => <content manually removed>
    [_supplier_email] => 
    [name] => RE: Test emails
    [urgency] => 3
    [itemtype] => 
    [requesttypes_id] => 2
    [entities_id] => 0
    [_ruleid] => 3
    [_no_history] => 
)
```

**Comment by LCBLondon** [comment]
See my [message from Aug 7](https://github.com/tomolimo/mailanalyzer/issues/40#issuecomment-670553317).
Some modifications are first required in the mailcollector class from GLPI in order to make the headers available for mailanalyzer.

**Comment by alisson9386** [comment]
Good Morning @tomolimo . I would like to know if there is any update when this update for glpi 9.5 comes out, I really need this plugin, it is very useful and extremely important in my context. I also want to congratulate him for being so useful to us, thank you very much.

**Comment by tomolimo** [comment]
Hello @alisson9386,
I'm going to work on the upgrade probably end of November or start of December 2020.
Stay tuned,
Thank you
Regards,
Tomolimo

**Comment by okvok** [comment]
Is it possible to integrate plugin into GLPI?

**Comment by tomolimo** [comment]
Hello @okvok 
Could you detail your question?
Thank you
Regards,
Tomolimo

**Comment by hobgoblinsmaster** [comment]
I think @okvok asks if the functionality could be integrated directly in GLPI instead of being a plugin.
I personally think it should be the case as the mail feature is barely usable by normal users without mailanalyzer and that the lacks of conversation understanding should be considerate as a bug in GLPI. ;-)

**Comment by tomolimo** [comment]
Hello @hobgoblinsmaster, hello @okvok 

I better understand now, thank you for the clarification.
I propose that you vote on (or comment) the already existing feature request on the GLPI user echo web site to ask for the plugin integration into GLPI core: [GLPI User Echo](https://glpi.userecho.com/fr/communities/1/topics/536-plugin-mailanalyzer-should-be-included-into-the-core-of-glpi)

Anyway, I'm going to work on the plugin upgrade to be compliant to GLPI 9.5

Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,

Currently working on the 9.5 migration 😃 

Thank you
Regards,

Tomolimo

**Comment by fgendorf** [comment]
Very very thank you!!!!
_________________________
Frederico Gendorf

**Comment by phamorais** [comment]
@tomolimo Thx!

**Comment by alarti** [comment]
@tomolimo many Thx ...
and if I can help in something (testing or qa) dont hesitate to ask me

**Comment by tomolimo** [comment]
Hello,
Currently there is a bug in GLPI that prevents the plugin to work correctly, see: https://github.com/glpi-project/glpi/issues/8345
It's going to be fixed in 9.5.4
Thank you,
Regards,
Tomolimo

**Comment by phamorais** [comment]
Hi @tomolimo 

But in this case, the Trasher correction didn't solve it?

**Comment by tomolimo** [comment]
Hello @phamorais 
Yes it solved the blocking point!
But of course it didn't solve the complete migration of the plugin, it was only a step forward the right direction...
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,
Good news, I've an alpha version running on 9.5.2 😃 
Official release will be available next week...
Thank you for your patience 😃 
Regards,
Tomolimo

**Comment by tomSDL** [comment]
Hi @tomolimo 

Thank you for updating this plugin. We will now be able to migrate to 9.5.

It really is appreciated. 

Regards

Tom

**Comment by alarti** [comment]
Thank you so much @tomolimo.

**Comment by sandromrsousa** [comment]
Hello,
Thx in advance for the update on plugin.
It will be compatible with last version 9.5.3?

**Comment by tomolimo** [comment]
Hello @sandromrsousa 
Yes, it will be compatible with 9.5.3
But it will need an update of two files from the 9.5.4: mailcollector.class.php and toolbox.class.php
I'll give instructions
Thank you
Regards,
Tomolimo

**Comment by okvok** [comment]
Hi,
I've just applied your [**fix**](https://github.com/glpi-project/glpi/commit/33490f4995a5bfb3bb6037c99da9e9e05bd3c983)  for testing from commit a148b9f but it does not work.
![image](https://user-images.githubusercontent.com/20252855/101460286-751b0400-394a-11eb-81bf-957de9eaf84b.png)

**Comment by tomolimo** [comment]
Hello @okvok 
Of course, as the plugin needed to be rewritten to be compliant with the new mail interface...
This fix was a prerequisite, and not the final fix for the compliance.
Thank you
Regards,
Tomolimo

**Comment by okvok** [comment]
thanx for your reply.

**Comment by tomolimo** [comment]
Hello to all,

Here is the first mailanalyzer release compliant with GLPI 9.5: https://github.com/tomolimo/mailanalyzer/releases/tag/2.0.0
Beware that it is actually compatible with 9.5.3, and that it needs a fix for two files `mailcollector.class.php`and `toolbox.class.php`. They are provided in the release.

If you really need to have a 9.5.2 compliant release of mailanalyzer, see this: https://github.com/tomolimo/mailanalyzer/issues/43

Thank you
Regards,
Tomolimo

**Comment by alarti** [comment]
Tested and working on 9.5.3 with fixed files....
Thank you so much @tomolimo

**Comment by tomolimo** [comment]
Hello,
For GLPI 9.5.2, see this: https://github.com/tomolimo/mailanalyzer/issues/43
Thank you,
Regards,
Tomolimo

**Comment by pierlaze** [comment]
Hello Tomolimo,
It tells me how to use the plugin for version 9.5.7 GLPI, I have installed it, but I don't know what else to do?
![image](https://user-images.githubusercontent.com/106604012/188890847-d3bfeeae-8f30-4d07-af3f-71c6f480231d.png)

**Comment by tomolimo** [comment]
Hello, @pierlaze 
Could you create another for another topic?
Thank you,
Regards,
Tomolimo
