### ISSUE TITLE
Errors when opening e-mail calls

### ISSUE THREAD

**Issue by phamorais** [tomolimo/mailanalyzer#41]
Hello!
I have a very strange problem. With Plugin 1.6.4 and GLPI 9.4.6, in some emails opened by email I get the following error

![image](https://user-images.githubusercontent.com/35368369/93544565-c65fbc80-f934-11ea-87d6-f68597fa75e3.png)

![image](https://user-images.githubusercontent.com/35368369/93544600-d8d9f600-f934-11ea-8f77-693d1a02c52c.png)

However, if I disable the plugin the error does not happen.

**Comment by tomolimo** [comment]
Hello @phamorais 

This error may occur when the plugin delete an email from the email server, and when GLPI mailgate tries to retreive the deleted email from the mail server.
This is due to the fact that the plugin will delete the email (duplicated email or followups to ticket,...) before GLPI gets it, but GLPI still have the email ID in its list, and GLPI will try to retrieve it from the email server.
In fact this is not a real error.

Thank you
Regards,
Tomolimo

**Comment by phamorais** [comment]
Hello! @tomolimo 
I confess I didn't understand. Does the plugin delete the email before the mailgate is executed?

**Comment by tomolimo** [comment]
Hello @phamorais 
I just checked again the process, here it is in detail:
On pre ticket add, then we do the following steps:
1. check if a ticket has already been created with this email (uses Thread-Index and messageID) to detect this. 
1. check if a ticket has already been created within the list of existing email references in current received email: in this case it add a followup to the existing ticket (if not solved, nor closed).

For both cases, If found, then it will reset current inputs to prevent a new ticket creation (ticket is already existing). But this will not delete the email from the IMAP inbox, so that next time the cron will be executed, then it will take again the same email... To prevent this behavior the plugin deletes the current email (and send it to the REFUSED folder), but doing that GLPI will throw the error you can see.

For me, this error is not linked to the issue you described in your email....

Could you check the logs when you have the troubles with GLPI that doesn't want to open the ticket. I already had such behavior in the past, and it was due to HTML tags in the email body (like < and >)

could you do some tests with plain text emails?

thank you,
regards,

Tomolimo

**Comment by phamorais** [comment]
@tomolimo 
Hello

Yes, I ran the test with simpler emails with plain text or some smaller attachments and the body of the email. And the vast majority was open normally

Follow the prints step by step like email --> **With the Plugin Activated**

1 - Ticket in INBOX awaiting cronjob

![image](https://user-images.githubusercontent.com/35368369/93952221-b1ad6b00-fd1e-11ea-85c4-fe38cdefb98d.png)

2 - mailgate run with sucess at 21:59pm

![image](https://user-images.githubusercontent.com/35368369/93952364-0650e600-fd1f-11ea-8c5c-c7190c1149e0.png)

3 - Mail sent to refused box

![image](https://user-images.githubusercontent.com/35368369/93952397-1b2d7980-fd1f-11ea-8ce1-f5de5457d8b0.png)

4 - Logs php-erros.log 

![image](https://user-images.githubusercontent.com/35368369/93952488-5465e980-fd1f-11ea-96e3-d5d10938a914.png)

5 - GLPI Erros in Receiver > List of not imported

![image](https://user-images.githubusercontent.com/35368369/93952774-12897300-fd20-11ea-87d8-2225bed6ad56.png)


**With the plugin disabled**



1 - Ticket in INBOX awaiting cronjob


![image](https://user-images.githubusercontent.com/35368369/93952972-8deb2480-fd20-11ea-833c-5a9e8a664927.png)


2 - mailgate run with sucess at 22:11pm

![image](https://user-images.githubusercontent.com/35368369/93953018-ace9b680-fd20-11ea-8bf3-4724d389f5b4.png)

3 - Mail sent to accepted box

![image](https://user-images.githubusercontent.com/35368369/93953054-bf63f000-fd20-11ea-8711-a91d7f31df75.png)

4 -  Logs php-erros.log 

![image](https://user-images.githubusercontent.com/35368369/93953118-f0442500-fd20-11ea-89c3-11efd45321d0.png)

5 - No refused itens in Recevers

![image](https://user-images.githubusercontent.com/35368369/93953148-0520b880-fd21-11ea-8655-f6ba1c2c5034.png)

6 - Ticket Open

![image](https://user-images.githubusercontent.com/35368369/93953170-1c5fa600-fd21-11ea-9f78-44cec1c234dc.png)

**Comment by phamorais** [comment]
Any?

**Comment by tomolimo** [comment]
Hello @phamorais 
Sorry for being long to answer, but I'm still doing short work due to Covid-19 crisis...
Give me some times to analyze your posts :) 
Thank you,
Regards,
Tomolimo

**Comment by phamorais** [comment]
@tomolimo 

thx!

**Comment by tomolimo** [comment]
Hello @phamorais 
Could you post in a zip file the email that cause troubles?
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @phamorais 
I have an idea, but I need to know which PHP version do you have?
And I need a sample of the email.
Thank you
Regards,
Tomolimo

**Comment by phamorais** [comment]
@tomolimo Hi!

Im use PHP 7.3.12

![image](https://user-images.githubusercontent.com/35368369/95469463-0e7f6700-0956-11eb-8d4d-6896842d7ab2.png)

I will send u a mail.  We can talk in telegram?

**Comment by tomolimo** [comment]
I'm sorry I don't use telegram, you may use my professional email address to send a zip file

**Comment by phamorais** [comment]
@tomolimo 

I Send to u !

**Comment by tomolimo** [comment]
Hello
Could you check?
I didn't reçoive tant email.
Thank you
Regards
Tomolimo

**Comment by tomolimo** [comment]
Sorry, I received an email  from cibra, was it yours?

**Comment by phamorais** [comment]
@tomolimo 

Yes
Cibra is my client.
Emails come from that customer

**Comment by tomolimo** [comment]
Hello @phamorais 

I cannot reproduce the issue: I can open the newly created ticket without troubles... I've tested with only the mailanalyzer plugin activated (the others were not enabled).
We need more details about:
GLPI configuration and PHP configuration: from menu: Setup > System from the [code] tag to [/code] tag

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Another question:
![image](https://user-images.githubusercontent.com/7569958/95556694-fb32d100-0a13-11eb-8a5e-454271a1a7b5.png)
You mentioned PHP 7.3.12 NTS?
And do you use Apache? That's strange to me to use NTS version if Apache is the web server... Normally NTS releases are only for FastCGI installation using IIS, and Apache is to use TS version of PHP. Do you have a mix of PHP versions?

**Comment by tomolimo** [comment]
Sorry, forget my previous POST: I made some tests with my Ubuntu VM, and I can see the same results than yours for the `php -v`

**Comment by phamorais** [comment]
@tomolimo HI

I did not understand. Can't you reproduce the error?

Follow / code


Server
--
Operating system: Linux  3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 PHP 7.3.12 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar, 	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, 	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, soap, sockets, sqlite3, standard, sysvmsg, sysvsem, 	sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.12 () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.4.14-MariaDB



Libraries
--
htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.3 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.2 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src) phpCas version 1.3.6 in (/usr/share/pear)




Plugins list
--
news                 Name: Alertas                        Version: 1.6.0      State: Enabled 	behaviors            Name: Comportamental                 Version: 2.2.2      State: Enabled 	datainjection        Name: Data injection                 Version: 2.7.1      State: Enabled 	escalade             Name: Escalonamento                  Version: 2.4.4      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.9.2      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.4+2.4    State: Enabled 	tag                  Name: Gerenciamento de Etiquetas     Version: 2.6.0      State: Enabled 	pdf                  Name: Imprimir em PDF                Version: 1.6.0      State: Enabled 	mailanalyzer         Name: Mail Analyzer                  Version: 1.6.4      State: Enabled 	dashboard            Name: Painel                         Version: 0.9.8      State: Enabled 	vip                  Name: VIP                            Version: 1.6.0      State: Enabled

**Comment by tomolimo** [comment]
I can't
Sorry

**Comment by tomolimo** [comment]
I suggest to do a test disabling all plugins but mailanalyzer. Means keep mailanalyzer enabled.

**Comment by phamorais** [comment]
@tomolimo Hi!

Sorry I didn't understand your follow up. Does this mean that you were unable to correct, or failed to reproduce the error?

![image](https://user-images.githubusercontent.com/35368369/96532892-2f539080-1263-11eb-81c3-3a28376ae032.png)


As for disabling all plugins leaving only the mailanalyzer, I did the test.

![image](https://user-images.githubusercontent.com/35368369/96533013-72156880-1263-11eb-82c9-299d1d0728f7.png)

The email was in the test box for receipt

![image](https://user-images.githubusercontent.com/35368369/96533180-cae50100-1263-11eb-8002-76699e22d613.png)

But Have Fail Again

![image](https://user-images.githubusercontent.com/35368369/96533396-3fb83b00-1264-11eb-8d56-7d8818e8b0db.png)

**Comment by tomolimo** [comment]
Hello @phamorais 

Thank you for the test you did.
Tell me in which language do you use GLPI? Portuguese?

My comment was: I cannot reproduce the issue with the email you sent to me.
And if I can't reproduce the issue, I can't fix it!
Could you zip the email and send it to me (instead of forwarding it to me) (use my professional email address)? As you are using Outlook, you may drag/drop the email to your desktop, and then zip it and sent it to me. This is the best way to do: it prevents loses of information, and permits that the email will arrive at my mailbox without being touch by the mail servers.

Thank you,
Regards,
Tomolimo

**Comment by phamorais** [comment]
@tomolimo Hi!

my language is portuguese.

I sent the email by email to the account  with the extension .msg and .rar (compressed)

![image](https://user-images.githubusercontent.com/35368369/96628147-3a9ccf80-12e8-11eb-8384-0b0d117c2d8d.png)

**Comment by tomolimo** [comment]
Hello @phamorais 
I've not been able to reproduce the issue 😢 
Could you try to reduce the complexity of issue to a very basic one, so that it will be possible to reproduce it?
Thank you
Regards,
Tomolimo

**Comment by phamorais** [comment]
Hello Tolimo!

In fact, there is no complexity. In fact, some e-mails are refused by GLPI, when PLugin is active, but there is no (or has not yet been discovered) the pattern that generates the error

For your knowledge .. I did a test on version 9.5.2 with the plugin disabled. And the same email q is refused in version 9.4.6, it is opened normally in 9.5.2.

Honestly, I will spend energy adapting and studying the update to 9.5.2, given the complexity of its correction in 9.4.6
