### ISSUE TITLE
 Mailanalyzer works on GLPI 9.5.2

### ISSUE THREAD

**Issue by alisson9386** [tomolimo/mailanalyzer#43]
Dear @tomolimo, as you requested, I am opening this instance because I need help to get mailanalyzer to work on GLPI version 9.5.2

Thank you very much in advance

**Comment by tomolimo** [comment]
Hello @alisson9386 

You need to modify three things:
1. the `plugins/mailanalyzer/setup.php` file of the plugin: You need to modify the minimal version from 9.5.3 to 9.5.2, you search and replace 9.5.3 by 9.5.2
2. you need to replace the `inc/toolbox.class.php` file by [toolbox.class.php.zip](https://github.com/tomolimo/mailanalyzer/files/5661530/toolbox.class.php.zip)
3. you need to replace the `inc/mailcollector.class.php` file by [mailcollector.class.php.zip](https://github.com/tomolimo/mailanalyzer/files/5661557/mailcollector.class.php.zip)

Thank you,
Regards,
Tomolimo

**Comment by alisson9386** [comment]
Greetings, @tomolimo!

I'm really happy that the plugin is working correctly.

Thank you very much.

**Comment by DulAltamirano** [comment]
Hola buenas tardes @tomolimo existe una versión del mailanalyzer para el glpi 9.5.1?

**Comment by tomolimo** [comment]
> Hola buenas tardes @tomolimo existe una versión del mailanalyzer para el glpi 9.5.1?

Hello @DulAltamirano 
Could post in English?
And could you post in a new issue? As this one is closed?
Thank you
Regards,
Tomolimo
