### ISSUE TITLE
[GLPI 9.5.3] Cannot collect mail when mailanalyzer enabled

### ISSUE THREAD

**Issue by tomSDL** [tomolimo/mailanalyzer#45]
Good Morning

Thanks for your work on this plugin. I have been waiting before migrating as this plugin is essential to us. 

I am migrating at the moment to 9.5.3 but cannot collect mail when mailanalyzer is enabled. With it disabled I get mail coming into tickets.

If I turn on debugging I get:

**Uncaught Exception Error: Call to undefined function imap_base64() in /var/www/html/glpi/plugins/mailanalyzer/hook.php at line 256**

Thank you

Tom

**Comment by fgendorf** [comment]
Hi, you must install php-imap extension.
_________________________
Frederico Gendorf

**Comment by tomSDL** [comment]
Hi @fgendorf 

Thank you so much. This resolved the issue!

Thanks again @tomolimo for your fantastic plugin.

**Comment by tomolimo** [comment]
Hello @fgendorf 
Thank you for the hint
I'll add this to the readme file.
Regards,
Tomolimo
