### ISSUE TITLE
Instalação V 9.5.0

### ISSUE THREAD

**Issue by ThiagoOliveira1792** [tomolimo/mailanalyzer#46]
Tomolino,

Primeiro quero parabeniza-lo pelo plugin

Estou tendo problemas para realizar a instalação do mesmo na versão do meu GLPI, ao colocar este na pasta de plugins e acessar a web me retorna a mensagem "Esse plug-in requerGLPI >= 9.5.3e <9.6."

GLPI 9.5.0 
PHP 7.0
Linux Centos7

**Comment by fgendorf** [comment]
Olá Thiago, acredito que você tenha que instalar a versão 9.5.3 e aplicar a
correção indicada pelo Tomolino.
Não é compatível com versão 9.5.0
_________________________
Frederico Gendorf

**Comment by ThiagoOliveira1792** [comment]
Realizei a atualização conforme informado porem ao instalar o plugin me retorna a seguinte msg de erro "This plugin requires upgraded versions of mailcollector.class.php and toolbox.class.php"

sou leigo tenham pasciencia cmg rsrs


<img width="940" alt="Capturar" src="https://user-images.githubusercontent.com/76490709/103048447-6d27aa80-456d-11eb-8ec3-91320df54ecd.PNG">

**Comment by fgendorf** [comment]
Please replace the original files on your installation by the following
https://github.com/tomolimo/mailanalyzer/releases/download/2.0.0/mailanalyzer-core-fixes.zip

_________________________
Frederico Gendorf

**Comment by ThiagoOliveira1792** [comment]
thanks, it worked and it's working
