### ISSUE TITLE
I Need a 9.5.2 Compliant Release of mailanalyzer

### ISSUE THREAD

**Issue by carlosPuigNavarro** [tomolimo/mailanalyzer#47]
Hello to all,

Here is the first mailanalyzer release compliant with GLPI 9.5: https://github.com/tomolimo/mailanalyzer/releases/tag/2.0.0
Beware that it is actually compatible with 9.5.3, and that it needs a fix for two files `mailcollector.class.php`and `toolbox.class.php`. They are provided in the release.

If you really need to have a 9.5.2 compliant release of mailanalyzer, please post in another issue, and I'll explain you how to do it.

Thank you
Regards,
Tomolimo

_Originally posted by @tomolimo in https://github.com/tomolimo/mailanalyzer/issues/40#issuecomment-740679439_

Hi @tomolimo!!

First of all, thanks for all the work you are dedicating.

I need a 9.5.2 compliant release of mailanalyzer, could you explain how to do it?

Thanks!!

**Comment by tomolimo** [comment]
Hello @carlosPuigNavarro 
See this: https://github.com/tomolimo/mailanalyzer/issues/43
Thank you
Regards,
Tomolimo
