### ISSUE TITLE
Error 9.5.2 imap_base64()

### ISSUE THREAD

**Issue by carlosPuigNavarro** [tomolimo/mailanalyzer#48]
Hello @alisson9386 

You need to modify three things:
1. the `plugins/mailanalyzer/setup.php` file of the plugin: You need to modify the minimal version from 9.5.3 to 9.5.2, you search and replace 9.5.3 by 9.5.2
2. you need to replace the `inc/toolbox.class.php` file by [toolbox.class.php.zip](https://github.com/tomolimo/mailanalyzer/files/5661530/toolbox.class.php.zip)
3. you need to replace the `inc/mailcollector.class.php` file by [mailcollector.class.php.zip](https://github.com/tomolimo/mailanalyzer/files/5661557/mailcollector.class.php.zip)

Thank you,
Regards,
Tomolimo

_Originally posted by @tomolimo in https://github.com/tomolimo/mailanalyzer/issues/43#issuecomment-740935928_

Hi @tomolimo,

I have followed the prompts, but now I get the following error:
"Uncaught Exception Error: Call to undefined function imap_base64() in /var/www/html/glpi/plugins/mailanalyzer/hook.php at line 256"

I've been looking, but can't figure out how to fix it.

Thank you very much.

**Comment by tomolimo** [comment]
Hello @carlosPuigNavarro 
see here: https://github.com/tomolimo/mailanalyzer/issues/45
Thank you,
Regards,
Tomolimo
