### ISSUE TITLE
GLPI 9.5.3 e-mails being refused

### ISSUE THREAD

**Issue by phamorais** [tomolimo/mailanalyzer#51]
Hello!

I am using version 9.5.3 and I have a strange behavior when I have the MailAnalyzer plugin enabled, Emails are declined.

![image](https://user-images.githubusercontent.com/35368369/106840677-65d0e200-667f-11eb-9bbf-6092bdfb2945.png)

![erro_mail](https://user-images.githubusercontent.com/35368369/106840168-5d2bdc00-667e-11eb-8af6-2e98f85d7d2e.gif)

No error is being displayed in "php-errors.log"

But in the apache log I get this

![image](https://user-images.githubusercontent.com/35368369/106840582-37eb9d80-667f-11eb-8f35-39a961867713.png)

If I disable the plugin the email is imported correctly

![mail_correct](https://user-images.githubusercontent.com/35368369/106840858-bcd6b700-667f-11eb-84fd-d894e1229288.gif)

Can u Help @tomolimo ?

**Comment by tomolimo** [comment]
Hello @phamorais 
Did you look into the Apache logs when you have succeeded to import the email?
I don't think that the errors shown in Apache logs are related to mailanalyzer plugin.
Regarding the email not imported into GLPI, several questions:
1. What is the profile of the email sender in GLPI?
2. It seems to me that it is an answer to another email? If so could you explain the email flow (initial sender, CC, BCC, ...)?

Thank you
Regards,
Tomolimo

**Comment by phamorais** [comment]
@tomolimo Hi!

 1 - The error occurs when opening tickets anonymously
 
2 - Really the example email is the response from the first email

The flow looks like this:

1 - Customer sends email to the account XTPO@outlook.com;

2 - The attendant inserts the followup in the GLPI;
3 - The Client receives the email;
4 - The Customer responds to the email by inserting more people in the "C / C" field;


This is still a test, we have not yet started production. Your placement was important, because in the test the email that is being sent for the collection of the GLPI is the Answer and not the original email.

I will test the flow again and give you feedback

**Comment by phamorais** [comment]
@tomolimo One Question
If the first email I am importing into GLPI is a "Email response", and if the first email does not exist in GLPI, it should open a new ticket ... correct?

**Comment by phamorais** [comment]
@tomolimo 

I tested it with a new email, with mail Analyzer enable

![image](https://user-images.githubusercontent.com/35368369/106895308-cd624e00-66ce-11eb-80c9-ae3688b8bbe5.png)

When trying to import the email through GLPI I get the error message

![image](https://user-images.githubusercontent.com/35368369/106895466-04386400-66cf-11eb-9941-0b36e93fbe1f.png)

![image](https://user-images.githubusercontent.com/35368369/106895517-14e8da00-66cf-11eb-9577-df9c4c2ddcf8.png)

Error in php-erros

![image](https://user-images.githubusercontent.com/35368369/106895609-34800280-66cf-11eb-9257-aa22536d603f.png)

**Comment by tomolimo** [comment]
Hello @phamorais 
As you can see by yourself, in the error log, there is nowhere mention of mailanalyzer plugin... Usually this means that the plugin has nothing to do with the error. More than that, the error is a connection error. The mailanalyzer plugin itself doesn't not connect to the mail server, it uses the information already gathered by the mail collector itself. The plugin doesn't modify connection information...

> @tomolimo One Question
> If the first email I am importing into GLPI is a "Email response", and if the first email does not exist in GLPI, it should open a new ticket ... correct?

This is correct. But, to be sure, you need to verify that the table `glpi_plugin_mailanalyzer_message_id` doesn't contains email id that may have been already input. To test, you can clear this table.

Thank you,
Regards,
Tomolimo

**Comment by phamorais** [comment]
Thanks, @tomolimo 

However, how can we understand that by deactivating the plugin, the email is imported?

**Comment by tomolimo** [comment]
Hello @phamorais 

> Thanks, @tomolimo
> 
> However, how can we understand that by deactivating the plugin, the email is imported?

This I cannot say... There is something wrong in the plugin, but the logs don't show it.
Could it be that there are some other logs? For example: `sql-errors.log`
I need to be able to reproduce the complete flow of emails.
Thank you
Regards,
Tomolimo

**Comment by phamorais** [comment]
@tomolimo 

In other tests this log appeared

![Laminas_mail](https://user-images.githubusercontent.com/35368369/106954853-218f2180-6713-11eb-8a4c-1913174495a8.PNG)


![image](https://user-images.githubusercontent.com/35368369/106955539-230d1980-6714-11eb-89d0-ae760a299da1.png)

**Comment by tomolimo** [comment]
Hello @phamorais 
Did you empty the `glpi_plugin_mailanalyzer_message_id` table before sending again and again the same email into GLPI?
As the plugin will prevent the integration if the reference of the email is present in this table...
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @phamorais 
I made a new release of the plugin to fix an issue that was a wrong returned parameter, but I don't think it will fix your troubles.
You may try it.
Thank you,
Regards,
Tomolimo

**Comment by phamorais** [comment]
@tomolimo Hi!

I tested several things yesterday .. and realized the following:

1 - According to your guidance, I noticed that some emails I was testing already had the ID filled in "glpi_plugin_mailanalyzer_message_id". So, when I tried to import again, the email was not important but there was no message explaining the reason, and this generated many doubts. A suggestion that I give a new version of the plugin is that when there are cases when we are trying to import an existing email in the column "glpi_plugin_mailanalyzer_message_id" Receive the message in GLPI, similar to the image below (I don't know if it's possible).

![image](https://user-images.githubusercontent.com/35368369/107040193-a32b9180-679d-11eb-9eb1-d4569b8dc367.png)


2 - As I understand it, GLPI does not validate if the email ID already exists, so it always imported the email. It made me think that your plugin was wrong, but it wasn't.

I will install the new version of the plugin as suggested, thank you for the cordial service ever

**Comment by tomolimo** [comment]
Hello @phamorais 
Thank you for your feedback.


> 1 - According to your guidance, I noticed that some emails I was testing already had the ID filled in "glpi_plugin_mailanalyzer_message_id". So, when I tried to import again, the email was not important but there was no message explaining the reason, and this generated many doubts. A suggestion that I give a new version of the plugin is that when there are cases when we are trying to import an existing email in the column "glpi_plugin_mailanalyzer_message_id" Receive the message in GLPI, similar to the image below (I don't know if it's possible).
> 
> ![image](https://user-images.githubusercontent.com/35368369/107040193-a32b9180-679d-11eb-9eb1-d4569b8dc367.png)

To understand the behavior of GLPI and of the plugin: in GLPI there is no way to interact with the mailcollector directly and to tell to it: don't create a ticket. The only way to prevent GLPI to create a ticket is to use a special hook called pre_item_add and to respond to this hook with "false" value. This unfortunately leads GLPI to think that the email was not imported -> the error you saw when  importing email manually from the receiver, and in the list of emails you can see the "Failed Operation" which is wrong is this case.



> 2 - As I understand it, GLPI does not validate if the email ID already exists, so it always imported the email. It made me think that your plugin was wrong, but it wasn't.

Exactly, you are right.


Thank you,
Regards,
Tomolimo
