### ISSUE TITLE
mailanalyzer for glpi 9.5.1

### ISSUE THREAD

**Issue by DulAltamirano** [tomolimo/mailanalyzer#54]
Hello @tomolimo, i have a question, ¿I can use plugin mailanalyzer 9.5.2 or mailanalyzer 9.5.3 for my glpi if is version 9.5.1?, this is because i dont find a mailanalyzer for 9.5.1 and i dont know if i put the others versions will be functional

Thank you

**Comment by tomolimo** [comment]
Hello @DulAltamirano 
I cannot say.
You may test using the version for the 9.5.2, applying the modifications that are explained here in #43 
Of course you'll have to change the min and max versions in setup.php file
Thank you
Regards,
Tomolimo

**Comment by DulAltamirano** [comment]
Thanks @tomolimo i could to install the plugin, but i dont know if for use the is necesary create a rule or how i can start to use?

**Comment by tomolimo** [comment]
Hello @DulAltamirano 

There is no rules to add!
Just enable the plugin like the others.
And you can test, sending emails to GLPI and have a look into the plugin table: `glpi_plugin_mailanalyzer_message_id`

Thank you,
Regards,
Tomolimo

**Comment by DulAltamirano** [comment]
Hello @tomolimo thank you...
this is functional... thanks for your time and quicky response.
