### ISSUE TITLE
Last version of toolbox.class.php does not work with glpi 9.5.4 version

### ISSUE THREAD

**Issue by marcosbarbosa-br** [tomolimo/mailanalyzer#57]
In the version 9.5.4 of GLPI, the file named inc/toolbox.class.php was changed and when i overwrite this file from plugin mailanalyzer, the system does not work properly.

**Comment by tomolimo** [comment]
Hello @marcosbarbosa-br 
The overwrite of the file should occur only for 9.5.3 and not for 9.5.4, see comment for release 2.0.1 here: https://github.com/tomolimo/mailanalyzer/releases/tag/2.0.1
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @marcosbarbosa-br 
I close this issue as there is no news from you, but feel free to re-open in case you need more details.
Thank you
Regards,
Olivier
