### ISSUE TITLE
GLPI 9.5.5

### ISSUE THREAD

**Issue by bsanra** [tomolimo/mailanalyzer#59]
I currently use GLPI 9.5.5, would you like to know if your plugin works in this version?

**Comment by tomolimo** [comment]
Hello @bsanra 
The version 2.0.1 is ok for 9.5.5
This 2.0.1 release is the one we are using with 9.5.5 internally.
Thank you
Regards,
Tomolimo

**Comment by bsanra** [comment]
Thanks for the information
