### ISSUE TITLE
The plugin seems not to work with GLPI 9.1

### ISSUE THREAD

**Issue by Dave89** [tomolimo/mailanalyzer#6]
Hello everyone,

I've just installed the plugin with GLPI 9.1 but it seems not to work when i send an email, the ticket is created so far everything is fine but when i, then, reply to all on that same email, i've got another ticket created on GLPI instead of adding a followup as it should be... so is there any setup or i just need to install and activate the plugin?

**Comment by tomolimo** [comment]
Hello,
Could you send me back your GLPi configuration?
It's there:
![image](https://cloud.githubusercontent.com/assets/7569958/20599011/28d5bb96-b24c-11e6-9cc6-3ab2288a1c8e.png)
Could you copy/paste here all the text between the [code] and [/code] tags
than you,
Tomolimo

**Comment by sebfun** [comment]
Not working also on 9.1.1.

Users who sends mails to helpdesk collector are mixed to existing mails.
I deactivated the plugin

Here's my configuration

[code]
 
GLPI 9.1.1 (/glpi => D:\xampp\htdocs\glpi)

Server

 
Operating system: Windows NT xxxxxxxxxx 5.2 build 3790 (Windows Server 2003 Standard Edition Service Pack 2) i586
PHP 5.4.31 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl,
	date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mhash,
	mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, session, soap, sockets, sqlite3, standard, tokenizer, wddx,
	xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="60" memory_limit="512M" post_max_size="16M" safe_mode="" session.save_handler="files"
	upload_max_filesize="15M" 
Software: Apache/2.4.10 (Win32) mod_authnz_sspi/0.1.0 OpenSSL/1.0.1h PHP/5.4.31 (Apache/2.4.10 (Win32) mod_authnz_sspi/0.1.0
	OpenSSL/1.0.1h PHP/5.4.31 Server at xxxxxxxxxxxxxx Port 80)
	Mozilla/5.0 (Windows NT 6.1; rv:49.0) Gecko/20100101 Firefox/49.0
Server Software: MySQL Community Server (GPL)
	Server Version: 5.5.39
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: localhost via TCP/IP
	
OKD:\xampp\htdocs\glpi/config : OK
OKD:\xampp\htdocs\glpi/files : OK
OKD:\xampp\htdocs\glpi/files/_dumps : OK
OKD:\xampp\htdocs\glpi/files/_sessions : OK
OKD:\xampp\htdocs\glpi/files/_cron : OK
OKD:\xampp\htdocs\glpi/files/_graphs : OK
OKD:\xampp\htdocs\glpi/files/_lock : OK
OKD:\xampp\htdocs\glpi/files/_plugins : OK
OKD:\xampp\htdocs\glpi/files/_tmp : OK
OKD:\xampp\htdocs\glpi/files/_rss : OK
OKD:\xampp\htdocs\glpi/files/_uploads : OK
OKD:\xampp\htdocs\glpi/files/_pictures : OK
OKD:\xampp\htdocs\glpi/files/_log : OK

Libraries

 
htmLawed version 1.1.21 in (D:\xampp\htdocs\glpi\lib\htmlawed)
phpCas version 1.3.4 in (D:\xampp\htdocs\glpi\vendor\jasig\phpcas\source)
PHPMailer version 5.2.16 in (D:\xampp\htdocs\glpi\vendor\phpmailer\phpmailer)
Zend Framework in (D:\xampp\htdocs\glpi\vendor\zendframework\zend-loader\src)
zetacomponents/graph in (D:\xampp\htdocs\glpi\vendor\zetacomponents\graph\src)
SimplePie version 1.4.1 in (D:\xampp\htdocs\glpi\vendor\simplepie\simplepie\library)
TCPDF version 6.2.12 in (D:\xampp\htdocs\glpi\vendor\tecnickcom\tcpdf)
ircmaxell/password-compat in (D:\xampp\htdocs\glpi\vendor\ircmaxell\password-compat\lib)
ramsey/array_column in (D:\xampp\htdocs\glpi\vendor\ramsey\array_column\src)
michelf/php-markdown in (D:\xampp\htdocs\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (D:\xampp\htdocs\glpi\vendor\true\punycode\src)
iacaml/autolink in (D:\xampp\htdocs\glpi\vendor\iamcal\lib_autolink)
sabre/vobject in (D:\xampp\htdocs\glpi\vendor\sabre\vobject\lib)

LDAP directories

 
Server: 'ldap://xxxxxxxx', Port: '389', BaseDN: 'OU=Utilisateurs & Groupes,OU=xwxxxxxx', Connection filter: none, RootDN: 'xxxxxxxxxxxxxx', Use TLS: none

SQL replicas

 
Not active

Notifications

 
Way of sending emails: SMTP (anonymous@xxxxxxx)

Mails receivers

 
Name: 'xxxxxxxxxxxx' Active: Yes
	Server: '{xxxxxxxxx/pop}' Login: '' Password: Yes

Plugins list

 
	addressing           Name: Adressage IP                   Version: 2.3.0      State: Not installed
	financialreports     Name: Arrêté du parc                 Version: 2.3.0      State: Enabled
	badges               Name: Badges                         Version: 2.2.0      State: Enabled
	databases            Name: Bases de données               Version: 1.9.0      State: Enabled
	accounts             Name: Comptes                        Version: 2.2.0      State: Enabled
	airwatch             Name: Connecteur Airwatch pour GLPi  Version: 0.90+1.1   State: Not activated
	consumables          Name: Demande de consommables        Version: 1.2.0      State: Enabled
	domains              Name: Domaines                       Version: 1.8.0      State: Enabled
	escalade             Name: Escalades                      Version: 2.1.0      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.1+1.0    State: Enabled
	genericobject        Name: Gestion d'objets               Version: 2.4.0      State: Enabled
	racks                Name: Gestion de baies               Version: 1.7.0      State: Enabled
	simcard              Name: Gestion de cartes SIM          Version: 1.4.2      State: Enabled
	manufacturersimports Name: Imports fabricants             Version: 1.9.0      State: Enabled
	mailanalyzer         Name: Mail Analyzer                  Version: 1.2.4      State: Not activated
	moreticket           Name: More ticket                    Version: 1.2.3      State: Enabled
	mreporting           Name: Plus de rapports               Version: 1.3.1      State: Enabled

[/code]

**Comment by sebfun** [comment]
I see in sender's mail that she was responding to another ticket number and the plugin has merged to another ticket number

**Comment by tomolimo** [comment]
@sebfun: it seems not the same issue than initial post, could you create another issue? Otherwise it's impossible to clarify anything? and then delete your posts from this issue?
thank you,
Tomolimo

**Comment by sebfun** [comment]
ok c'est fait

**Comment by tomolimo** [comment]
thank you

**Comment by Dave89** [comment]
Hello,
Sorry for the late reply. Here it is:

`
[code]
 
GLPI 9.1 ( => /var/www/html/glpi)

Server

 
Operating system: Linux glpi.dev.tmb.cd 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64
PHP 5.4.16 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bz2, calendar, ctype, curl, date, ereg,
	exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, json, ldap, libxml, mbstring, mhash, mysql, mysqli, openssl,
	pcre, pdo_mysql, pdo_sqlite, session, shmop, sockets, sqlite3, standard, tokenizer, xml, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) PHP/5.4.16 ()
	Mozilla/5.0 (Windows NT 6.1; rv:50.0) Gecko/20100101 Firefox/50.0
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.15-log
	Server SQL Mode: 
	Parameters: glpidev@10.33.1.11/glpidev
	Host info: 10.33.1.11 via TCP/IP
	
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
OK/var/www/html/glpi/files/_log : OK
Web access to the files directory, should not be allowed
Check the .htaccess file and the web server configuration.
OKSELinux mode is Disabled

Libraries

 
htmLawed version 1.1.21 in (/var/www/html/glpi/lib/htmlawed)
phpCas version 1.3.4 in (/var/www/html/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.16 in (/var/www/html/glpi/vendor/phpmailer/phpmailer)
Zend Framework in (/var/www/html/glpi/vendor/zendframework/zend-loader/src)
zetacomponents/graph in (/var/www/html/glpi/vendor/zetacomponents/graph/src)
SimplePie version 1.4.1 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.12 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
ircmaxell/password-compat in (/var/www/html/glpi/vendor/ircmaxell/password-compat/lib)
ramsey/array_column in (/var/www/html/glpi/vendor/ramsey/array_column/src)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iacaml/autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)

LDAP directories

 
Server: '10.33.0.53', Port: '389', BaseDN: 'ou=people,dc=dev,dc=tmb,dc=cd', Connection filter: none, RootDN:
		'uid=glpi,ou=LDAP,dc=dev,dc=tmb,dc=cd', Use TLS: none

SQL replicas

 
Not active

Notifications

 
Way of sending emails: SMTP (alerts-glpi@tmb.cd@10.32.0.229)

Mails receivers

 
Name: 'helpdeskdev@tmb.cd' Active: No
	Server: '{10.32.0.29/imap/ssl/novalidate-cert/notls}' Login: 'helpdeskdev@tmb.cd' Password: Yes

Plugins list

 
	appliances           Name: Applicatifs                    Version: 2.2        State: Enabled
	archires             Name: Architectures réseau           Version: 2.3        State: Not activated
	barcode              Name: Barcode                        Version: 0.90+1.0   State: Not activated
	databases            Name: Bases de données               Version: 1.8.1      State: Not activated
	positions            Name: Cartographie                   Version: 4.2.1      State: Not activated
	certificates         Name: Certificats                    Version: 2.1.1      State: Not activated
	behaviors            Name: Comportements                  Version: 1.1        State: Not activated
	accounts             Name: Comptes                        Version: 2.1.1      State: Not activated
	domains              Name: Domaines                       Version: 1.7.0      State: Not activated
	environment          Name: Environnement                  Version: 1.9.0      State: Not activated
	escalation           Name: Escalation ticket              Version: 0.90+1.0   State: Not activated
	formcreator          Name: Formulaires                    Version: 0.90-1.3.4 State: Enabled
	fusioninventory      Name: FusionInventory                Version: 0.90+1.4   State: Not activated
	geninventorynumber   Name: Génération de numéros d'invent Version: 0.85+1.0   State: Not activated
	genericobject        Name: Gestion d'objets               Version: 2.4.0      State: Enabled
	order                Name: Gestion des commandes          Version: 1.9.5      State: Enabled
	mailanalyzer         Name: Mail Analyzer                  Version: 1.2.4      State: Enabled
	mreporting           Name: Plus de rapports               Version: 0.90+1.2   State: Not installed
	dashboard            Name: Tableau de bord                Version: 0.7.7      State: Enabled
	ticketcleaner        Name: Ticket Cleaner                 Version: 2.0.4      State: Enabled

[/code]
A copier/coller lors d'une demande d'assistance
`

**Comment by Dave89** [comment]
Hello,

Sorry for the late reply.

GLPI 9.1 ( => /var/www/html/glpi)

Server

 
Operating system: Linux glpi.dev.tmb.cd 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64
PHP 5.4.16 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bz2, calendar, ctype, curl, date, ereg,
	exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, json, ldap, libxml, mbstring, mhash, mysql, mysqli, openssl,
	pcre, pdo_mysql, pdo_sqlite, session, shmop, sockets, sqlite3, standard, tokenizer, xml, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) PHP/5.4.16 ()
	Mozilla/5.0 (Windows NT 6.1; rv:50.0) Gecko/20100101 Firefox/50.0
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.15-log
	Server SQL Mode: 
	Parameters: glpidev@10.x.x.x/glpidev
	Host info: 10.x.x.x via TCP/IP
	
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
OK/var/www/html/glpi/files/_log : OK
Web access to the files directory, should not be allowed
Check the .htaccess file and the web server configuration.
OKSELinux mode is Disabled

Libraries

 
htmLawed version 1.1.21 in (/var/www/html/glpi/lib/htmlawed)
phpCas version 1.3.4 in (/var/www/html/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.16 in (/var/www/html/glpi/vendor/phpmailer/phpmailer)
Zend Framework in (/var/www/html/glpi/vendor/zendframework/zend-loader/src)
zetacomponents/graph in (/var/www/html/glpi/vendor/zetacomponents/graph/src)
SimplePie version 1.4.1 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.12 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
ircmaxell/password-compat in (/var/www/html/glpi/vendor/ircmaxell/password-compat/lib)
ramsey/array_column in (/var/www/html/glpi/vendor/ramsey/array_column/src)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iacaml/autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)

LDAP directories

 
Server: '10.x.x.x', Port: '389', BaseDN: 'ou=people,dc=dev,dc=xxx,dc=cd', Connection filter: none, RootDN:
		'uid=glpi,ou=LDAP,dc=dev,dc=xxx,dc=cd', Use TLS: none

SQL replicas

 
Not active

Notifications

 
Way of sending emails: SMTP (alerts-glpi@xxx.cd@10.32.0.229)

Mails receivers

 
Name: 'helpdeskdev@xxx.cd' Active: No
	Server: '{10.x.x.x/imap/ssl/novalidate-cert/notls}' Login: 'helpdeskdev@xxx.cd' Password: Yes

Plugins list

 
	appliances           Name: Applicatifs                    Version: 2.2        State: Enabled
	archires             Name: Architectures réseau           Version: 2.3        State: Not activated
	barcode              Name: Barcode                        Version: 0.90+1.0   State: Not activated
	databases            Name: Bases de données               Version: 1.8.1      State: Not activated
	positions            Name: Cartographie                   Version: 4.2.1      State: Not activated
	certificates         Name: Certificats                    Version: 2.1.1      State: Not activated
	behaviors            Name: Comportements                  Version: 1.1        State: Not activated
	accounts             Name: Comptes                        Version: 2.1.1      State: Not activated
	domains              Name: Domaines                       Version: 1.7.0      State: Not activated
	environment          Name: Environnement                  Version: 1.9.0      State: Not activated
	escalation           Name: Escalation ticket              Version: 0.90+1.0   State: Not activated
	formcreator          Name: Formulaires                    Version: 0.90-1.3.4 State: Enabled
	fusioninventory      Name: FusionInventory                Version: 0.90+1.4   State: Not activated
	geninventorynumber   Name: Génération de numéros d'invent Version: 0.85+1.0   State: Not activated
	genericobject        Name: Gestion d'objets               Version: 2.4.0      State: Enabled
	order                Name: Gestion des commandes          Version: 1.9.5      State: Enabled
	mailanalyzer         Name: Mail Analyzer                  Version: 1.2.4      State: Enabled
	mreporting           Name: Plus de rapports               Version: 0.90+1.2   State: Not installed
	dashboard            Name: Tableau de bord                Version: 0.7.7      State: Enabled
	ticketcleaner        Name: Ticket Cleaner                 Version: 2.0.4      State: Enabled

**Comment by tomolimo** [comment]
Hello,
Could post back the content of the table `glpi_plugin_mailanalyzer_message_id`?
Thank you,
Regards,
Tomolimo

**Comment by Dave89** [comment]
Hello,

There it is:

MySQL [glpidev]> select * from glpi_plugin_mailanalyzer_message_id;
+----+-------------------------------------------------------+------------+
| id | message_id                                            | ticket_id  |
+----+-------------------------------------------------------+------------+
|  1 | <15445445.6260376.1479983702271.JavaMail.root@tmb.cd> | 2016021105 |
|  2 | <14605589.6261161.1479983761556.JavaMail.root@tmb.cd> | 2016021106 |
|  3 | <16805458.6295349.1479987804218.JavaMail.root@tmb.cd> | 2016021107 |
|  4 | <27791555.6297495.1479988208620.JavaMail.root@tmb.cd> | 2016021108 |
|  5 | <22390254.6304934.1479989499786.JavaMail.root@tmb.cd> | 2016021109 |
|  6 | <19825016.6306405.1479989685708.JavaMail.root@tmb.cd> | 2016021110 |
|  7 | <29397204.6309187.1479990062465.JavaMail.root@tmb.cd> | 2016021111 |
|  8 | <1875069.6309528.1479990109547.JavaMail.root@tmb.cd>  | 2016021112 |
|  9 | <16885796.6311791.1479990358286.JavaMail.root@tmb.cd> | 2016021113 |
| 10 | <17867621.6311941.1479990406758.JavaMail.root@tmb.cd> | 2016021114 |
| 11 | <19106161.6312514.1479990518359.JavaMail.root@tmb.cd> | 2016021115 |
+----+-------------------------------------------------------+------------+
11 rows in set (0.00 sec)

**Comment by tomolimo** [comment]
Hello
Sorry for my late answer.
Could you check if there is any errors in logs?
Thank you

**Comment by sudhakarang** [comment]
Hai,
              I too face the issues in Glpi9.1.1 mailanalyzer plugin . Ticket creation happens with forwarder mail id rather than the original requester from id .

[code]
 
GLPI 9.1.1 (/glpi => /usr/share/glpi)

Server
 
Operating system: Linux kits 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64
PHP 5.5.9-1ubuntu4.20 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2,
	calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, json, ldap,
	libxml, mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcntl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.7 (Ubuntu) (Apache/2.4.7 (Ubuntu) Server at 10.20.1.5 Port 80)
	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.5.53-0ubuntu0.14.04.1
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
OK/usr/share/glpi/config : OK
OK/usr/share/glpi/files : OK
OK/usr/share/glpi/files/_dumps : OK
OK/usr/share/glpi/files/_sessions : OK
OK/usr/share/glpi/files/_cron : OK
OK/usr/share/glpi/files/_graphs : OK
OK/usr/share/glpi/files/_lock : OK
OK/usr/share/glpi/files/_plugins : OK
OK/usr/share/glpi/files/_tmp : OK
OK/usr/share/glpi/files/_rss : OK
OK/usr/share/glpi/files/_uploads : OK
OK/usr/share/glpi/files/_pictures : OK
OK/usr/share/glpi/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries
 
htmLawed version 1.1.21 in (/usr/share/glpi/lib/htmlawed)
phpCas version 1.3.4 in (/usr/share/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.16 in (/usr/share/glpi/vendor/phpmailer/phpmailer)
Zend Framework in (/usr/share/glpi/vendor/zendframework/zend-loader/src)
zetacomponents/graph in (/usr/share/glpi/vendor/zetacomponents/graph/src)
SimplePie version 1.4.1 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.12 in (/usr/share/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iacaml/autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)

LDAP directories
 
Server: '10.20.1.11', Port: '389', BaseDN: 'DC=pyad,DC=local', Connection filter: '(& (objectCategory=person) )', RootDN:
		'Administrator@pyad.local', Use TLS: none
Server: '10.24.0.50', Port: '389', BaseDN: 'DC=kgkhk,DC=com', Connection filter: '(& (objectCategory=person) )', RootDN:
		'administrator@kgkhk.com', Use TLS: none
Server: '10.160.2.2', Port: '389', BaseDN: 'DC=trinity,DC=th', Connection filter: '(objectCategory=person)', RootDN:
		'Administrator@trinity.th', Use TLS: none
Server: '172.20.6.20', Port: '389', BaseDN: 'DC=SZADM,DC=LOCAL', Connection filter: '(& (objectCategory=person) )', RootDN:
		'administrator@szadm.local', Use TLS: none
Server: '172.20.20.22', Port: '389', BaseDN: 'DC=PYDTA_AD,DC=local,DC=com', Connection filter: none, RootDN:
		'administrator@pydta_ad.local.com', Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (anonymous@10.20.1.56)

Mails receivers
 
Name: 'itsupport.bkk@trinitycreations.co.th' Active: No
	Server: '{10.20.1.56:143/imap/novalidate-cert/notls/norsh/debug}' Login: 'itsupport.bkk@trinitycreations.co.th' Password: Yes
Name: 'IT-SUPPORT-China' Active: Yes
	Server: '{10.20.1.56:143/imap/notls/norsh/debug}' Login: 'ithelpdesk.panyu@kgkmail.com' Password: Yes

Plugins list
 
	domains              Name: Domains                        Version: 1.7.0      State: New
	fusioninventory      Name: FusionInventory                Version: 9.1+1.0    State: Enabled
	addressing           Name: IP Adressing                   Version: 2.5.0      State: Enabled
	mailanalyzer         Name: Mail Analyzer                  Version: 1.2.4      State: Enabled
	mydashboard          Name: My Dashboard                   Version: 1.2.1      State: Not installed
	ocsinventoryng       Name: OCS Inventory NG               Version: 1.2.2      State: Enabled
	racks                Name: Rack enclosures management     Version: 1.7.0      State: Enabled
	tasklists            Name: Tasks list                     Version: 1.0.0      State: Not installed

OCS Inventory NG
Host: localhost
Connection: Ok
Use the OCSNG software dictionary: Yes
[/code]

**Comment by tomolimo** [comment]
Hello,
This https://github.com/tomolimo/mailanalyzer/issues/6#issuecomment-268131468 seems not to be the same issue than the one described in the header part of the current issue.
Could you post in another issue? please,
Thank you,
Tomolimo

**Comment by tomolimo** [comment]
Hello
Could tell me which email client you are using?
And also if possible could you zip the emails you sent first and replyto to me?

The plugin is using internal email client generated ids to search for existing tickets. Could it be possible that your email client send new ids when 'reply to all' is used? Or could it happen that the subject of the email has been changed? In this case the email client will generate new ids which indicate that the conversation is not the same than previous. When "Re:" or "FW:" are added to email subject, the email client will not change the ids, so that in this case mailanalyzer will be able to merge the new emails into one ticket (adding followups).

regards,
Tomolimo

**Comment by Dave89** [comment]
Hi Tomolimo,

The only thing i can tell you is that, i'm using: **Zimbra Webmail Client** with **Zimbra Mail Server**... unfortunately i can not forward the email since i'm currently having a limited access to my mail account since i'm currently away from my testing platform

regards,
Dave

**Comment by tomolimo** [comment]
I'll wait for your return to your testing platform :)

**Comment by tomolimo** [comment]
No news!
please feel free to re-open
