### ISSUE TITLE
Ticket_ID int(11) unsigned for error on plugin behaviors with format 'ymdxxxx'

### ISSUE THREAD

**Issue by jairockman** [tomolimo/mailanalyzer#62]
**Describe the bug**

Hi @tomolimo  there is a bug with the plugin behaviors with format 'ymdxxxx' https://github.com/yllen/behaviors/issues/4.

This cause tickets aren't created correctly, and I experienced some similar errors with the plugin mailanalyzer, because the column ticket_id is in int(10) so the maximum value is 2147483647, and in my tickets the format is ymdxxxx so for example for the date 2201040001 doesn't work, and emails have be not linked correctly to the ticket ID, but instead to 2147483647 (this ticket ID doesn't exists).

**Screenshots**

![image](https://user-images.githubusercontent.com/56606032/148134713-68eb46cd-1808-4d6e-835d-72e6a35035ca.png)

**Additional context**

I have changed the data type of the column from int(10) to int(11) unsigned and this worked for me:
![image](https://user-images.githubusercontent.com/56606032/148135200-6cb3b75e-1e6a-457c-8ade-144823965202.png)

But this worked for new incomming replied emails, because the already replied emails I don't know how to correct this ticket id state. I also tried to delete the record of the emails with this ticket ID, and reprocessed the email from the receiver, but again is assigned the ticket ID: 2147483647.

What can I do?

**Comment by jairockman** [comment]
Hi again sorry,

For this:

> But this worked for new incomming replied emails, because the already replied emails I don't know how to correct this ticket id state. I also tried to delete the record of the emails with this ticket ID, and reprocessed the email from the receiver, but again is assigned the ticket ID: 2147483647.
> 
> What can I do?

I had to searched every messaged ID from the email inbox processed related to the ticket in GLPI, found the original first email that fire-up the creation ticket, I corrected the ticket_id from 2147483647 to the correct ticket ID from GLPI, I searched the other message id from the email's replied, I searched them in the column message_id, correct the ticket_id from 2147483647 to the correct ticket ID or deleted that row, and reprocessed the emails again with te receiver. And worked like a charm! 

But I don't know if I'm doing well, it's necessary to change from int(10) to int(11) unsigned?

**Comment by tomolimo** [comment]
Hello @jcervantes-sipecom 
Sorry for this bug due to the year 2022...
Yes I think you've done well when you've expanded the ticket_id field to 11 INT
Thank you
Regards,
Tomolimo

**Comment by jairockman** [comment]
Thanks @tomolimo, but it is not necessary to change the data type on the plugin per default? I mean I have changed manually, but in the future someone else will have the same issue.

**Comment by tomolimo** [comment]
Yes of course, I'm going to provide a new release for that...
