### ISSUE TITLE
GLPI 10

### ISSUE THREAD

**Issue by epigraphe** [tomolimo/mailanalyzer#66]
Good day.
Is the plugin planned to work with glpi 10?
I installed it but I get the error:

*** PHP User Warning (512): Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/glpi/src/Plugin.php at line 1410

Is it possible to run it under version 10, since it does not have this functionality?

**Comment by tomolimo** [comment]
Hello @epigraphe 
Yes this is planned, but currently not scheduled :)
Thank you,
Regards,
Tomolimo

**Comment by epigraphe** [comment]
Thanks.
We are very, very much looking forward to it.
You have the most important plugin for GLPI to work

**Comment by sghebuz** [comment]
Hello @tomolimo I think this plugin is a must for glpi, do you think we can sponsor the compatibility with version 10? thanks

**Comment by tomolimo** [comment]
Hello @sghebuz 
Currently, this a problem of time, not a problem of money 😃
Thank you for your proposal, but I would prefer if you propose a pull request for the compatibility :)
Thank you,
Regards,
Tomolimo

**Comment by sghebuz** [comment]
eheh same here :-D it was worth a shot

**Comment by jlangone** [comment]
Hi @tomolimo as @sghebuz said this plugin is one of the most important tools for glpi to work.
Can you estimate when it will be a compatible version with glpi 10?
Thank u very much, regards from UY.

**Comment by tomolimo** [comment]
Hello @jlangone 
Probably for September.
But in the meanwhile, you propose a PR to update it to GLPI 10.0
Thank you,
Regards,
Tomolimo

**Comment by shuriban** [comment]
Hello @tomolimo
For GLPI 10.0. replace `$iterator->next();` to `$iterator->current();`
https://github.com/glpi-project/glpi/issues/6010#issuecomment-1062857744

**Comment by empereira** [comment]
> Hello @tomolimo For GLPI 10.0. replace `$iterator->next();` to `$iterator->current();` [glpi-project/glpi#6010 (comment)](https://github.com/glpi-project/glpi/issues/6010#issuecomment-1062857744)

Hi, In which file should this change take place?

**Comment by tomolimo** [comment]
Fixed by https://github.com/tomolimo/mailanalyzer/releases/tag/3.0.0
