### ISSUE TITLE
how to use mailanalyzer plugin?

### ISSUE THREAD

**Issue by pierlaze** [tomolimo/mailanalyzer#70]
How to use the mailanalyzer plugin in GLPI 9.5.7 , I have it installed; but I don't know how to use it?
![image](https://user-images.githubusercontent.com/106604012/188927832-9320df40-09b7-4a72-b88d-691e88253a03.png)

**Comment by tomolimo** [comment]
Hello @pierlaze 
There is no special config to do...
The purpose of this plugin is to automatically merge emails within the same discussion (thread or topic).
There no configuration to achieve this.
Thank you,
Regards,
Tomolimo
