### ISSUE TITLE
php error classname on line 1426

### ISSUE THREAD

**Issue by fakie77** [tomolimo/mailanalyzer#72]
Hello and thanks for your plugin,

I have: 
GLPI 10.0.1 with collector based on email office365 with oauth2 authentification
Plugin oauthimap 1.4.1
Plugin mailanalyzer 1.6.0 (last version)

The problem: when i try to use collector to collect mails in the oauth2 email, i obtain a blank screen on page : glpi/front/mailcollector.form.php and i don't collect any mail.

And when I disable mailanalyzer plugin, it's work fine.

In logs php, i see this error:
PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/ticket.php

If you need more information, tell me

Thanks for your help

Hervé

**Comment by tomolimo** [comment]
Hello @fakie77 
Could you look into the php error log file, there is a complete call stack, and not only the last error message?
Thank you to post the complete call stack
Thank you,
Regards,
Tomolimo

**Comment by fakie77** [comment]
Hello @tomolimo 

Complete php log: 
[Mon Oct 03 17:47:41.077904 2022] [php7:warn] [pid 864] [client 192.168.12.3:31946] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/config.form.php
[Mon Oct 03 17:47:41.119169 2022] [php7:warn] [pid 864] [client 192.168.12.3:31946] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/config.form.php
[Mon Oct 03 17:47:41.442307 2022] [php7:warn] [pid 864] [client 192.168.12.3:31946] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/index.php?noAUTO=1
[Mon Oct 03 17:47:41.444984 2022] [php7:warn] [pid 864] [client 192.168.12.3:31946] PHP Warning:  error_log(/var/www/html/glpi/files/_log/cron.log): failed to open stream: Permission denied in /var/www/html/glpi/src/Toolbox.php on line 572, referer: https://172.30.240.22/glpi/index.php?noAUTO=1
[Mon Oct 03 17:47:41.467518 2022] [php7:warn] [pid 865] [client 192.168.12.3:31948] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/index.php?noAUTO=1
[Mon Oct 03 17:47:41.498173 2022] [php7:warn] [pid 874] [client 192.168.12.3:31961] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/index.php?noAUTO=1
[Mon Oct 03 17:47:41.522453 2022] [php7:warn] [pid 892] [client 192.168.12.3:31964] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/index.php?noAUTO=1
[Mon Oct 03 17:47:41.548139 2022] [php7:warn] [pid 785] [client 192.168.12.3:31962] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/index.php?noAUTO=1
[Mon Oct 03 17:47:41.571270 2022] [php7:warn] [pid 789] [client 192.168.12.3:31963] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/index.php?noAUTO=1
[Mon Oct 03 17:47:41.589502 2022] [php7:warn] [pid 890] [client 192.168.12.3:31965] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/index.php?noAUTO=1
[Mon Oct 03 17:47:41.612530 2022] [php7:warn] [pid 865] [client 192.168.12.3:31948] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/index.php?noAUTO=1
[Mon Oct 03 17:47:41.637866 2022] [php7:warn] [pid 874] [client 192.168.12.3:31961] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/index.php?noAUTO=1
[Mon Oct 03 17:47:41.659688 2022] [php7:warn] [pid 892] [client 192.168.12.3:31964] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/index.php?noAUTO=1
[Mon Oct 03 17:47:41.682486 2022] [php7:warn] [pid 785] [client 192.168.12.3:31962] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/index.php?noAUTO=1
[Mon Oct 03 17:47:54.367811 2022] [php7:warn] [pid 864] [client 192.168.12.3:31971] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/index.php?noAUTO=1
[Mon Oct 03 17:47:55.016475 2022] [php7:warn] [pid 864] [client 192.168.12.3:31971] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/index.php?noAUTO=1
[Mon Oct 03 17:47:56.101852 2022] [php7:warn] [pid 892] [client 192.168.12.3:31995] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:56.147983 2022] [php7:warn] [pid 891] [client 192.168.12.3:31997] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:56.186103 2022] [php7:warn] [pid 874] [client 192.168.12.3:31996] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:56.221753 2022] [php7:warn] [pid 864] [client 192.168.12.3:31971] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:56.250982 2022] [php7:warn] [pid 785] [client 192.168.12.3:31999] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:56.289098 2022] [php7:warn] [pid 906] [client 192.168.12.3:31998] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:56.325828 2022] [php7:warn] [pid 892] [client 192.168.12.3:31995] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:56.363257 2022] [php7:warn] [pid 891] [client 192.168.12.3:31997] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:56.402966 2022] [php7:warn] [pid 874] [client 192.168.12.3:31996] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:56.442789 2022] [php7:warn] [pid 864] [client 192.168.12.3:31971] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:56.472129 2022] [php7:warn] [pid 785] [client 192.168.12.3:31999] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:56.891580 2022] [php7:warn] [pid 785] [client 192.168.12.3:31999] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:56.936625 2022] [php7:warn] [pid 864] [client 192.168.12.3:31971] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:56.974759 2022] [php7:warn] [pid 864] [client 192.168.12.3:31971] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:57.011074 2022] [php7:warn] [pid 874] [client 192.168.12.3:31996] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:57.052137 2022] [php7:warn] [pid 785] [client 192.168.12.3:31999] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:57.094936 2022] [php7:warn] [pid 874] [client 192.168.12.3:31996] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:57.135695 2022] [php7:warn] [pid 785] [client 192.168.12.3:31999] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php
[Mon Oct 03 17:47:57.191846 2022] [php7:warn] [pid 785] [client 192.168.12.3:31999] PHP Warning:  Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php on line 1426, referer: https://172.30.240.22/glpi/front/central.php


Thanks for your help

Regards,

Herve

**Comment by tomolimo** [comment]
Hello @fakie77 
Where did you get this php error log?
Was it in `/var/www/html/glpi/files/_log/`?
Thank you,
Regards,
Tomolimo

**Comment by fakie77** [comment]
Hello @tomolimo 

No, at var/log/apache2/error.log

At /var/www/html/glpi/files/_log/ we have: 

2022-10-04 17:31:03] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined method Toolbox::unclean_html_cross_side_scripting_deep() in /var/www/html/glpi/plugins/mailanalyzer/hook.php at line 194
  Backtrace :
  plugins/mailanalyzer/hook.php:262                  PluginMailAnalyzer::getTextFromHtml()
  src/Plugin.php:1464                                PluginMailAnalyzer::plugin_pre_item_add_mailanalyzer()
  src/CommonDBTM.php:1252                            Plugin::doHook()
  src/MailCollector.php:842                          CommonDBTM->add()
  src/MailCollector.php:1830                         MailCollector->collect()
  src/CronTask.php:1018                              MailCollector::cronMailgate()
  front/cron.php:84                                  CronTask::launch()
  
[2022-10-04 17:31:04] glpiphplog.WARNING:   *** PHP User Warning (512): Unknown attributes "classname" used in "PluginMailAnalyzer" class registration in /var/www/html/glpi/src/Plugin.php at line 1426
  Backtrace :
  src/Plugin.php:1426                                trigger_error()
  plugins/mailanalyzer/setup.php:10                  Plugin::registerClass()
  src/Plugin.php:288                                 plugin_init_mailanalyzer()
  src/Plugin.php:238                                 Plugin::load()
  inc/includes.php:86                                Plugin->init()
  front/plugin.form.php:40                           include()


Sorry for this.
Thanks

**Comment by tomolimo** [comment]
Hello @fakie77 
Where did you get this mailanalyzer version (1.6.0 has never been released)?
The correct version for GLPI 10.0 is the 3.0.0, (see: https://github.com/tomolimo/mailanalyzer/releases)
Could you upgrade to 3.0.0?
Thank you,
Regards,
Tomolimo

**Comment by fakie77** [comment]
Hello @tomolimo,

Sorry, i just found my error thanks to your last comment... When i have updated mailanalyzer from precedent version, some files were not updated and were mixed with version 3.0.0 . So i just erase the folder and reinstall the plugin and now i am on version 3.0.0 and it's work.

I'm sorry for waste your time with this. Thanks for all.

Regards,

Herve
