### ISSUE TITLE
10.0.3 compatibility

### ISSUE THREAD

**Issue by empereira** [tomolimo/mailanalyzer#73]
hello @tomolimo,

When will it be compatible with glpi version 10.0.3?

**Comment by tomolimo** [comment]
Hello @empereira 
In a near future :)
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @empereira 
Did you try the current release which is compatible with GLPI 10.0.x?
Thank you,
Regards,
Tomolimo

**Comment by gjfmlj** [comment]
The current version is compatible with glpi10.0.0, but 10.0.3 does not work.

**Comment by tomolimo** [comment]
Hello @gjfmlj 
Could you give more details?
Could you check the PHP error logs and SQL error log files?*
Thank you
Regards,
Tomolimo

**Comment by empereira** [comment]
> Hello @empereira Did you try the current release which is compatible with GLPI 10.0.x? Thank you, Regards, Tomolimo

Hello Tomolino,

I changed the code to accept version 10.0.3 and at first it installed and is active.

How can I make sure it is working?

**Comment by tomolimo** [comment]
Hello @empereira 
Why did you change code, and where?
You just need to take the 10.0.x compatible release and install it like for any plugins.
Thank you,
Regards,
Tomolimo

**Comment by gjfmlj** [comment]
[mysql-log.zip](https://github.com/tomolimo/mailanalyzer/files/10123637/mysql-log.zip)
Please help to view this log file，Thanks.

**Comment by tomolimo** [comment]
Hello @gjfmlj 
That's look like SQL query log, but not like SQL error logs...
Could you check the PHP error logs and SQL error log files, they are in the `glpi-path/files/_log` folder?
Thank you,
Regards,
Tomolimo

**Comment by gjfmlj** [comment]
root@glpi:/var/www/html/glpi/files/_log# cat php-errors.log
[2022-12-03 15:23:54] glpiphplog.WARNING:   *** PHP Warning (2): mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /var/www/html/glpi/src/DBmysql.php at line 250
  Backtrace :
  src/DBmysql.php:250                                mysqli->real_connect()
  src/DBmysql.php:209                                DBmysql->connect()
  src/DBConnection.php:412                           DBmysql->__construct()
  src/DBConnection.php:501                           DBConnection::switchToMaster()
  inc/config.php:116                                 DBConnection::establishDBConnection()
  inc/includes.php:53                                include_once()
  ajax/notifications_ajax.php:36                     include()

I didn't find any useful information in the log.

**Comment by tomolimo** [comment]
Hello @gjfmlj 
Try to use IP address instead of the SQL server name, to prevent the name resolution warning.
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,
As th issue was the compatibility with GPI 10.0.x and as it has been develloped, I close this issue.
If you have some troubles using this release https://github.com/tomolimo/mailanalyzer/releases/tag/3.0.0, please create a new issue.
Thank you,
Regards,
Tomolimo
