### ISSUE TITLE
Mail Analyzer Stop Get Ticket 

### ISSUE THREAD

**Issue by mailmamen** [tomolimo/mailanalyzer#74]
Hi Sir,

Im using glpi version 9.5.7 Since September 2022 this plugin disabled by our server because all ticket from email stopped. When we are disabled the plugins all email succesfully to create the ticket. 

is there any issue from this plugins or what we can do with our server.

Thanks
Ismail

**Comment by tomolimo** [comment]
Hello @mailmamen 
Could you give plugin version?
Could you detail steps to reproduce this?
Thank you,
Regards,
Tomolimo

**Comment by mailmamen** [comment]
Hi Sir,

my version using 2.0.2
GPL v2+

For reproduce not yet because when i saw on this post it for GLPI 10.0.0.
My GLPI still on using 9.5.7

Thanks

**Comment by tomolimo** [comment]
Hello @mailmamen 
With GLPI 9.5.7, you may try the latest pluguin release: https://github.com/tomolimo/mailanalyzer/releases/tag/2.1.0
Thank you,
Regards,
Tomolimo

**Comment by mailmamen** [comment]
Hi Sir,

Thanks for update the information,  After tried update we got another issue if we open page plugins internal server error 500.

My step is
1. Open plugins and uninstall mail analyzer previous version.
2. upload the new plugin in the same folder before (not replace but rename previous folder and upload 1 directory mail analyzer new version.
3. when open the page plugins in GLPI I got that error internal server error 500 (only page plugins)  but another page workwel.

If there some mistaken with my step sir?

Thankyou

**Comment by tomolimo** [comment]
Hello @mailmamen 
You can't have folders that are renamed in the plugins folder. You must move it somewhere else.
GLPI is looking into all folders in plugins folder to get plugins infos.
Thank you,
Regards,
Tomolimo

**Comment by mailmamen** [comment]
Hi Sir,

Many thanks for your assist. As of now overall work well.

Regards,
Ismail

**Comment by tomolimo** [comment]
Hello @mailmamen 
You're welcome,
Regards,
Tomolimo
