### ISSUE TITLE
Tickets creates on forwarder id rather than from id 'On Behalf Of' 

### ISSUE THREAD

**Issue by sudhakarang** [tomolimo/mailanalyzer#8]
Hai,
I face the issues in Glpi9.1.1 mailanalyzer plugin . Ticket creation happens with forwarder mail id rather than the original requester from id when I forward someone request  I mean 'On Behalf Of' some one 

[code]

GLPI 9.1.1 (/glpi => /usr/share/glpi)

Server

Operating system: Linux kits 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64
PHP 5.5.9-1ubuntu4.20 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2,
calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, json, ldap,
libxml, mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcntl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets,
standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files"
upload_max_filesize="20M"
Software: Apache/2.4.7 (Ubuntu) (Apache/2.4.7 (Ubuntu) Server at 10.20.1.5 Port 80)
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
Server Software: (Ubuntu)
Server Version: 5.5.53-0ubuntu0.14.04.1
Server SQL Mode:
Parameters: root@localhost/glpi
Host info: Localhost via UNIX socket

OK/usr/share/glpi/config : OK
OK/usr/share/glpi/files : OK
OK/usr/share/glpi/files/_dumps : OK
OK/usr/share/glpi/files/_sessions : OK
OK/usr/share/glpi/files/_cron : OK
OK/usr/share/glpi/files/_graphs : OK
OK/usr/share/glpi/files/_lock : OK
OK/usr/share/glpi/files/_plugins : OK
OK/usr/share/glpi/files/_tmp : OK
OK/usr/share/glpi/files/_rss : OK
OK/usr/share/glpi/files/_uploads : OK
OK/usr/share/glpi/files/_pictures : OK
OK/usr/share/glpi/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries

htmLawed version 1.1.21 in (/usr/share/glpi/lib/htmlawed)
phpCas version 1.3.4 in (/usr/share/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.16 in (/usr/share/glpi/vendor/phpmailer/phpmailer)
Zend Framework in (/usr/share/glpi/vendor/zendframework/zend-loader/src)
zetacomponents/graph in (/usr/share/glpi/vendor/zetacomponents/graph/src)
SimplePie version 1.4.1 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.12 in (/usr/share/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iacaml/autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)

LDAP directories

Server: '10.20.1.11', Port: '389', BaseDN: 'DC=pyad,DC=local', Connection filter: '(& (objectCategory=person) )', RootDN:
'Administrator@pyad.local', Use TLS: none
Server: '10.24.0.50', Port: '389', BaseDN: 'DC=kgkhk,DC=com', Connection filter: '(& (objectCategory=person) )', RootDN:
'administrator@kgkhk.com', Use TLS: none
Server: '10.160.2.2', Port: '389', BaseDN: 'DC=trinity,DC=th', Connection filter: '(objectCategory=person)', RootDN:
'Administrator@trinity.th', Use TLS: none
Server: '172.20.6.20', Port: '389', BaseDN: 'DC=SZADM,DC=LOCAL', Connection filter: '(& (objectCategory=person) )', RootDN:
'administrator@szadm.local', Use TLS: none
Server: '172.20.20.22', Port: '389', BaseDN: 'DC=PYDTA_AD,DC=local,DC=com', Connection filter: none, RootDN:
'administrator@pydta_ad.local.com', Use TLS: none

SQL replicas

Not active

Notifications

Way of sending emails: SMTP (anonymous@10.20.1.56)

Mails receivers

Name: 'itsupport.bkk@xyz.com' Active: No
Server: '{10.20.1.56:143/imap/novalidate-cert/notls/norsh/debug}' Login: 'itsupport.bkk@trinitycreations.co.th' Password: Yes
Name: 'IT-SUPPORT-China' Active: Yes
Server: '{10.20.1.56:143/imap/notls/norsh/debug}' Login: 'ithelpdesk.panyu@xyz.com' Password: Yes

Plugins list

domains              Name: Domains                        Version: 1.7.0      State: New
fusioninventory      Name: FusionInventory                Version: 9.1+1.0    State: Enabled
addressing           Name: IP Adressing                   Version: 2.5.0      State: Enabled
mailanalyzer         Name: Mail Analyzer                  Version: 1.2.4      State: Enabled
mydashboard          Name: My Dashboard                   Version: 1.2.1      State: Not installed
ocsinventoryng       Name: OCS Inventory NG               Version: 1.2.2      State: Enabled
racks                Name: Rack enclosures management     Version: 1.7.0      State: Enabled
tasklists            Name: Tasks list                     Version: 1.0.0      State: Not installed

OCS Inventory NG
Host: localhost
Connection: Ok
Use the OCSNG software dictionary: Yes
[/code]

**Comment by tomolimo** [comment]
Hello,
Sorry for my late answer.
Could you detail step by step what has been done, so that I can reproduce the problem?
Thank you,
Regards,
Tomolimo

**Comment by sudhakarang** [comment]
Hello,
          When a user send a mail to my email id for some request .I am trying to forward the mail to support email id for which we have configured receiver in glpi . The mail which i forward on behalf of some one creates the ticket with requester as me whereas I am only a forwarder and original from: source id is some other user .
               Also my profile in Glpi is super-admin .Is this have something to do with mail analyzer logic.Should my profile be post only for this to happen ?

Thanks & regards 
Sudhakar

**Comment by tomolimo** [comment]
Hello,
The behavior you are describing is GLPi standard one.

But Mailanalyzer plugin adds a new behavior: the so called 'OnBehalfOf'.

But to be activated, this mechanism needs a flag in the ticket, see screen copy below:

![image](https://cloud.githubusercontent.com/assets/7569958/21516412/50304228-ccd8-11e6-81dc-a2c80393e087.png)

1. As seen on the screen copy, when you want to forward an email 'OnBehalfOf' to a GLPi receiver, you need to have `##From LastName, FirstName` in the message that is forwarded. A regular expression `/##From: ([_a-z0-9-\' ]+), ([_.a-z0-9- ]+)/i` will verify this syntax, so it must be really like shown. 

 In `LastName` authorized chars are: 

- letters from '`a`' to '`z`', 
- underscores '`_`', 
- digits from '`0`' to '`9`', 
- dashes '`-`', whitespaces '` `' 
- single quotes '`'`'. 

And in `FirstName` authorized chars are: 

- letters from '`a`' to '`z`', 
- underscores '`_`', 
- digits from '`0`' to '`9`', 
- dashes '`-`', 
- whitespaces '` `' 
- dots '`.`'. 

The comparison is case insensitive.

2. The GLPi user who matches `LastName, FirstName` must be unique in GLPi
1. This user must have at least one email address

regards,
Tomolimo

**Comment by C-Duv** [comment]
Little side note, when I redirect someone's e-mail to the GLPI's collected e-mail address, I use [_Mail Redirect_](https://addons.mozilla.org/fr/thunderbird/addon/mailredirect/) Thunderbird extension: which does not do a "forward", but a "bounce".
(Disclaimer: I do not use the mailanalyzer plugin, yet)

**Comment by tomolimo** [comment]
Anyway, if you use the given syntax `##From:...` and respecting the above statements, you should be able to create ticket 'OnBehalfOf' 
regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello, I hope explanation were OK to solve your issue.
