### ISSUE TITLE
##From: tag is working to forward emails in version 3.1.1?

### ISSUE THREAD

**Issue by empereira** [tomolimo/mailanalyzer#83]
hello @tomolimo ,

##From: tag is working to forward emails in version 3.1.1?

**Comment by tomolimo** [comment]
Hello @empereira 
Yes it should...
Could you describe your issue?
Could you give version of GLPI?
Could you post PHP and SQL log files, if errors occured?
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @empereira 
This is the wrong repo... See [MailBehaviours plugin](https://github.com/tomolimo/mailbehaviours) for the ##From feature
Thank you
Regards,
Tomolimo
