### ISSUE TITLE
[Improvement] Allow Supplier Followups

### ISSUE THREAD

**Issue by jairockman** [tomolimo/mailanalyzer#84]
When a Supplier assigned to a ticket, response an email the response is rejected, not added as followup. 

I know that anonymous followup should be activated to allow a Supplier reply to an email, but this followup is only allowed when the supplier reply the email that GLPI notifications send containing these lines:

```
=-=-=-= To respond by email, type above this line =-=-=-=

=_=_=_= To respond by email, type below this line =_=_=_=
```

But when using mailanalyzer, we use directly mail, not just Glpi notification, so the suppplier reply to the mail, and that isn't include the above lines.

There's a way that mailanalyzer allows the reply of a Supplier and add it as a followup?

**Comment by tomolimo** [comment]
Hello @jcervantes-sipecom 
You may create a "post-only" (= "self-service") user with the supplier email: this should permit the creation of the followup.
Even if the user is de-activated (or in the trashbin) GLPI will permit the creation of a ticket (or followup when combined with mailanalyzer plugin).
Thank you,
Regards,
Tomolimo

**Comment by jairockman** [comment]
> Hello @jcervantes-sipecom You may create a "post-only" (= "self-service") user with the supplier email: this should permit the creation of the followup. Even if the user is de-activated (or in the trashbin) GLPI will permit the creation of a ticket (or followup when combined with mailanalyzer plugin). Thank you, Regards, Tomolimo

Thank you @tomolimo for the suggestion, actually I know this, in the forums and group chats recommended the same. But I personally think has a user without using is kind of insecure, that's way I guess this could be an improvement in the plugin, that a Supplier can reply with the email, so is not necessary creating a user.

But if this is not in roadmap or even consider necessary, so this ticket can be closed.

I'm grateful for your reply and hard-worked plugin.
