### ISSUE TITLE
Erratic behavior in plugin

### ISSUE THREAD

**Issue by daniespejel** [tomolimo/mailanalyzer#9]
Hello!

i'm testing this plugin and i'm not sure if is working properly.

user send email direct to my address and add in cc field the mail address for the glpi receiver, the ticket is created and the answers to all are added as followup, when the user send an email to glpi receiver and other addresses are in cc field the ticket is created, but the answers to all of people in cc are creating new tickets.

Summarizing, if glpi mail receiver is in 'cc' field all works great, but if mail receiver is in 'to' field it's create a new ticket for every answer, it's this behavior ok or i'm doing something wrong?

and another point, when the mail receiver task process multiples emails and one of the first email is a reply from a user in 'cc' the plugin add a blank register to the glpi_plugin_mailanalyzer_message_id tbale in DB and the next processed email are created without followups or mixing the tickets followups

Regards and thank you for your amazing work!

**Comment by tomolimo** [comment]
Hello,
Thank you for using this plugin :)
Could you tell me which version of GLPI are you using?
Thank you,
Regards,
Tomolimo

**Comment by daniespejel** [comment]
GLPI 9.1.1 on Windows Server 2012 R2

Adding my System Info from glpi and screenshot from DB table. mailanalizer is currently disabled 
![2017-01-18 08_05_31-bkp_glpidb_glpi_plugin_mailanalyzer_message_id_ - heidisql 9 4 0 5143](https://cloud.githubusercontent.com/assets/14876947/22068662/532c7648-dd5b-11e6-9fa9-295fa6710b6f.png)


Information about system installation and configuration

[code]
 
GLPI 9.1.1 ( => C:\xampp_5_6_8\htdocs\glpi)

Server

 
Operating system: Windows NT ----- 6.2 build 9200 (Windows Server 2012 Standard Edition) i586
PHP 5.6.8 apache2handler (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
	bcmath, bz2, calendar, ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap,
	libxml, mbstring, mcrypt, mhash, mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, session, snmp, soap,
	sockets, sqlite3, standard, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="1024M" post_max_size="128M" safe_mode="" session.save_handler="files"
	upload_max_filesize="256M" 
Software: Apache/2.4.12 (Win32) mod_authnz_sspi/0.1.0 OpenSSL/1.0.1l PHP/5.6.8 (Apache/2.4.12 (Win32) mod_authnz_sspi/0.1.0
	OpenSSL/1.0.1l PHP/5.6.8 Server at ------ Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0
Server Software: MySQL Community Server (GPL)
	Server Version: 5.6.24
	Server SQL Mode: 
	Parameters: glpi@127.0.0.1/glpidb
	Host info: 127.0.0.1 via TCP/IP
	
OKC:\xampp_5_6_8\htdocs\glpi/config : OK
OKC:\xampp_5_6_8\htdocs\glpi/files : OK
OKC:\xampp_5_6_8\htdocs\glpi/files/_dumps : OK
OKC:\xampp_5_6_8\htdocs\glpi/files/_sessions : OK
OKC:\xampp_5_6_8\htdocs\glpi/files/_cron : OK
OKC:\xampp_5_6_8\htdocs\glpi/files/_graphs : OK
OKC:\xampp_5_6_8\htdocs\glpi/files/_lock : OK
OKC:\xampp_5_6_8\htdocs\glpi/files/_plugins : OK
OKC:\xampp_5_6_8\htdocs\glpi/files/_tmp : OK
OKC:\xampp_5_6_8\htdocs\glpi/files/_rss : OK
OKC:\xampp_5_6_8\htdocs\glpi/files/_uploads : OK
OKC:\xampp_5_6_8\htdocs\glpi/files/_pictures : OK
OKC:\xampp_5_6_8\htdocs\glpi/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries

 
htmLawed version 1.1.21 in (C:\xampp_5_6_8\htdocs\glpi\lib\htmlawed)
phpCas version 1.3.4 in (C:\xampp_5_6_8\htdocs\glpi\vendor\jasig\phpcas\source)
PHPMailer version 5.2.16 in (C:\xampp_5_6_8\htdocs\glpi\vendor\phpmailer\phpmailer)
Zend Framework in (C:\xampp_5_6_8\htdocs\glpi\vendor\zendframework\zend-loader\src)
zetacomponents/graph in (C:\xampp_5_6_8\htdocs\glpi\vendor\zetacomponents\graph\src)
SimplePie version 1.4.1 in (C:\xampp_5_6_8\htdocs\glpi\vendor\simplepie\simplepie\library)
TCPDF version 6.2.12 in (C:\xampp_5_6_8\htdocs\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\xampp_5_6_8\htdocs\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\xampp_5_6_8\htdocs\glpi\vendor\true\punycode\src)
iacaml/autolink in (C:\xampp_5_6_8\htdocs\glpi\vendor\iamcal\lib_autolink)
sabre/vobject in (C:\xampp_5_6_8\htdocs\glpi\vendor\sabre\vobject\lib)

LDAP directories

 
Server: '----', Port: '-----', BaseDN: 'dc=-----,dc=mx', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'cn=-------,cn=---,dc=-----,dc=mx', Use TLS: none

SQL replicas

 
Not active

Notifications

 
Way of sending emails: SMTP (soporte@xxxx@xxxx)

Mails receivers

 
Name: 'soporte@-----' Active: Yes
	Server: '{mail.-----:110/pop}' Login: 'soporte@xxxxx' Password: Yes

Plugins list

 
	positions            Name: Cartografía                    Version: 4.3.1      State: Enabled
	dashboard            Name: Dashboard                      Version: 0.7.9      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.1+1.1    State: Enabled
	mailanalyzer         Name: Mail Analyzer                  Version: 1.2.4      State: Not activated

[/code]
To copy/paste in your support request


![image](https://cloud.githubusercontent.com/assets/14876947/22068673/60dd523a-dd5b-11e6-8b2d-d3076a2840ee.png)

**Comment by tomolimo** [comment]
Thank you
I'll test this, and keep you informed

**Comment by daniespejel** [comment]
thank you :)

**Comment by tomolimo** [comment]
Seems fixed by 227eb647dacab1be4b7cf6ab680165be82fae6ca

**Comment by tomolimo** [comment]
Hello,
Latest release really fixes this issue
Regards,
Tomolimo

**Comment by daniespejel** [comment]
Thank you @tomolimo. I'm going to check it 
Regards!

**Comment by tomolimo** [comment]
Be sure to clear the empty rows before running new version.
